=== jan-ldwg/site_manager_templates/v1/schemas/deviceType.schema.json
{
  "$schema": "https://json-schema.org/draft/2020-12/schema",
  "title": "deviceType",
  "description": "JSON document describing a new deviceType",
  "type": "object",
  "required": ["version", "id", "name", "manufacturerId", "rackType"],
  "additionalProperties": false,
  "properties": {
    "version": {
      "description": "Version number of the template. Minor version must be increased with every change. Major version must only be changed when targeting a different API version.",
      "type": "string",
      "pattern": "^\\d{1,2}\\.\\d{1,2}$"
    },
    "id": {
      "description": "Id of the device type. Consists of id of manufacturer followed by id of device type. See documentation for rules.",
      "type": "string",
      "pattern": "^(?=.{1,48}$)(?!.*--)[a-z](?:[a-z-]{0,14}[a-z])?-[a-z0-9](?:[a-z0-9-]*[a-z0-9])?$",
      "maxLength": 48
    },
    "name": {
      "description": "Name of the device as given by manufacturer",
      "type": "string",
      "maxLength": 256
    },
    "manufacturerId": {
      "description": "Id of the manufacturer of the device type.",
      "type": "string",
      "pattern": "^(?!.*--)[a-z](?:[a-z-]{0,14}[a-z])$",
      "maxLength": 16
    },
    "orderCode": {
      "description": "Order code for the device type as used by the manufacturer.",
      "type": ["string", "null"]
    },
    "sku": {
      "description": "SKU for the device type as used by the manufacturer.",
      "type": ["string", "null"]
    },
    "gtin": {
      "description": "GTIN for the device type as used by the manufacturer.",
      "type": ["string", "null"],
      "maxLength": 14
    },
    "climateLoad": {
      "description": "The maximum heat dissipation of the device type in watt.",
      "type": ["integer", "null"],
      "minimum": 0
    },
    "weight": {
      "description": "Weigth of the device type in gram.",
      "type": ["integer", "null"],
      "minimum": 0
    },
    "width": {
      "description": "Width of the device type in millimeter.",
      "type": ["integer", "null"],
      "minimum": 0
    },
    "height": {
      "description": "Height of the device type in millimeter.",
      "type": ["integer", "null"],
      "minimum": 0
    },
    "depth": {
      "description": "Depth of the device type in millimeter.",
      "type": ["integer", "null"],
      "minimum": 0
    },
    "rackType": {
      "description": "The type of rack the device can be mounted in.",
      "enum": ["19INCH", "NONE"]
    },
    "rackHeight": {
      "description": "The height the device occupies inside a rack in units of that rack type.",
      "type": "integer"
    },
    "rackDepth": {
      "description": "The distance between the mounting plane of the rack and the rear most potrusion of the device in mm.",
      "type": "integer",
      "minimum": 0
    },
    "portTypes": {
      "description": "List of all types of ports on the device type.",
      "type": "array",
      "items": {
        "type": "object",
        "required": ["name", "connectorId", "subinterfaceTypes"],
        "additionalProperties": false,
        "properties": {
          "name": {
            "description": "Name of the port, as printed on the device.",
            "type": "string"
          },
          "connectorId": {
            "description": "Id of the connector.",
            "type": "string",
            "pattern": "^[A-Za-z0-9](?:[A-Za-z0-9]|[_.](?=[A-Za-z0-9]))*_(?:f|m|h)$"
          },
          "subinterfaceTypes": {
            "description": "List of all subinterfaceTypes included in the portType",
            "type": "array",
            "items": {
              "type": "object",
              "required": ["name", "direction", "compatibleSignalTypes"],
              "additionalProperties": false,
              "properties": {
                "name": {
                  "description": "The name of the subinterfaceType. Left null if only one subinterface exists on the port. Else a descriptive name, like Ch. 1, GPI IN 3, etc.",
                  "type": ["string", "null"]
                },
                "direction": {
                  "description": "Direction of the subinterFaceType. See documentation for explainations of the possible values.",
                  "enum": [
                    "IN",
                    "OUT",
                    "INOUT",
                    "BIDI",
                    "UP",
                    "DOWN",
                    "FRONT",
                    "REAR"
                  ]
                },
                "compatibleSignalTypes": {
                  "description": "List of signal types that are compatible with this port.",
                  "type": "array",
                  "items": {
                    "type": "string",
                    "pattern": "^(?!.*--)(?:[a-z](?:[a-z-]{0,14}[a-z])?_)?[A-Z0-9]+(?:_[A-Z0-9]+)*$"
                  },
                  "uniqueItems": true
                },
                "pinout": {
                  "description": "An array describing the pins asscociated with the subinterface.",
                  "type": ["array", "null"],
                  "items": {
                    "type": "object",
                    "additionalProperties": false,
                    "properties": {
                      "pin": {
                        "description": "A human readable identification of the pin, e.g. its number or center/shield for BNC.",
                        "type": "string"
                      },
                      "signal": {
                        "description": "The signal present on that pin. This is not the signalType, but something more basic like positive, negative, GND, etc.",
                        "type": "string"
                      }
                    }
                  }
                },
                "addInfo": {
                  "description": "An object that contains additional information, depending on the signalType",
                  "type": ["object", "null"],
                  "additionalProperties": false,
                  "properties": {
                    "AC_POWER": {
                      "type": "object",
                      "additionalProperties": false,
                      "properties": {
                        "minV": {
                          "description": "Minimum acceptable voltage of a power input or output",
                          "type": "number"
                        },
                        "maxV": {
                          "description": "Maximum acceptable voltage of a power input or output",
                          "type": "number"
                        },
                        "minF": {
                          "description": "Minimum acceptable frequency of a power input or output",
                          "type": "number"
                        },
                        "maxF": {
                          "description": "Maximum acceptable frequency of a power input or output",
                          "type": "number"
                        },
                        "maxP": {
                          "description": "Maximum acceptable power of a power input or output",
                          "type": "number"
                        }
                      }
                    },
                    "AC_POWER_PE": {
                      "type": "object",
                      "additionalProperties": false,
                      "properties": {
                        "minV": {
                          "description": "Minimum acceptable voltage of a power input or output",
                          "type": "number"
                        },
                        "maxV": {
                          "description": "Maximum acceptable voltage of a power input or output",
                          "type": "number"
                        },
                        "minF": {
                          "description": "Minimum acceptable frequency of a power input or output",
                          "type": "number"
                        },
                        "maxF": {
                          "description": "Maximum acceptable frequency of a power input or output",
                          "type": "number"
                        },
                        "maxP": {
                          "description": "Maximum acceptable power of a power input or output",
                          "type": "number"
                        }
                      }
                    },
                    "THREE_PHASE_POWER": {
                      "type": "object",
                      "additionalProperties": false,
                      "properties": {
                        "minV": {
                          "description": "Minimum acceptable voltage of a power input or output",
                          "type": "number"
                        },
                        "maxV": {
                          "description": "Maximum acceptable voltage of a power input or output",
                          "type": "number"
                        },
                        "minF": {
                          "description": "Minimum acceptable frequency of a power input or output",
                          "type": "number"
                        },
                        "maxF": {
                          "description": "Maximum acceptable frequency of a power input or output",
                          "type": "number"
                        },
                        "maxP": {
                          "description": "Maximum acceptable power of a power input or output",
                          "type": "number"
                        }
                      }
                    },
                    "DC_POWER": {
                      "type": "object",
                      "additionalProperties": false,
                      "properties": {
                        "minV": {
                          "description": "Minimum acceptable voltage of a power input or output",
                          "type": "number"
                        },
                        "maxV": {
                          "description": "Maximum acceptable voltage of a power input or output",
                          "type": "number"
                        },
                        "maxP": {
                          "description": "Maximum acceptable power of a power input or output",
                          "type": "number"
                        }
                      }
                    },
                    "POE": {
                      "oneOf": [
                        {
                          "type": "object",
                          "additionalProperties": false,
                          "required": ["role"],
                          "properties": { "role": { "const": "NONE" } }
                        },
                        {
                          "type": "object",
                          "additionalProperties": false,
                          "required": ["role", "maxP"],
                          "properties": {
                            "role": { "const": "PSE" },
                            "maxP": {
                              "type": "number",
                              "exclusiveMinimum": 0
                            }
                          }
                        },
                        {
                          "type": "object",
                          "additionalProperties": false,
                          "required": ["role", "maxP", "required"],
                          "properties": {
                            "role": { "const": "PD" },
                            "maxP": {
                              "type": "number",
                              "exclusiveMinimum": 0
                            },
                            "required": { "type": "boolean" }
                          }
                        }
                      ]
                    }
                  }
                }
              }
            }
          }
        }
      }
    },
    "moduleSlotTypes": {
      "description": "List of all types of module slots on the device type.",
      "type": "array",
      "items": {
        "type": "object",
        "required": [
          "name",
          "compatibleModuleSlotFormFactors",
          "compatibleModuleTypes",
          "incompatibleModuleTypes"
        ],
        "additionalProperties": false,
        "properties": {
          "name": {
            "description": "Name of the module slot, as labeled on the device.",
            "type": "string"
          },
          "canSpan": {
            "description": "Indicates wether a module can span into the next slot",
            "type": "boolean"
          },
          "compatibleModuleSlotFormFactors": {
            "description": "List of module slot factors that can physically fit into the slot.",
            "type": "array",
            "uniqueItems": true,
            "items": {
              "type": "string",
              "pattern": "^[a-z0-9]+(?:-[a-z0-9]+)*$"
            }
          },
          "compatibleModuleTypes": {
            "description": "List of module types that are guranteed by the manufacturer to work in this slot.",
            "type": "array",
            "uniqueItems": true,
            "items": {
              "type": "string",
              "pattern": "^(?=.{1,48}$)(?!.*--)[a-z](?:[a-z-]{0,14}[a-z])?-[a-z0-9](?:[a-z0-9-]*[a-z0-9])?$"
            }
          },
          "incompatibleModuleTypes": {
            "description": "List of module types that are guranteed by the manufacturer not work in this module slot.",
            "type": "array",
            "uniqueItems": true,
            "items": {
              "type": "string",
              "pattern": "^(?=.{1,48}$)(?!.*--)[a-z](?:[a-z-]{0,14}[a-z])?-[a-z0-9](?:[a-z0-9-]*[a-z0-9])?$"
            }
          }
        }
      }
    }
  }
}

=== jan-ldwg/site_manager_templates/v1/deviceTypes/blackmagic/blackmagic-multiview-4-hd.json
{
  "id": "blackmagic-multiview-4-hd",
  "version": "1.0",
  "name": "MultiView 4 HD",
  "manufacturerId": "blackmagic",
  "orderCode": null,
  "sku": null,
  "gtin": null,
  "climateLoad": 6,
  "weight": 242,
  "width": 134,
  "height": 22,
  "depth": 92,
  "rackType": "NONE",
  "rackHeight": 0,
  "rackDepth": 0,
  "portTypes": [
    {
      "name": "POWER +6 to 36V",
      "connectorId": "BARREL_XX_f",
      "subinterfaceTypes": [
        {
          "name": "",
          "direction": "IN",
          "pinout": [],
          "compatibleSignalTypes": ["DC_POWER"],
          "addInfo": {
            "DC_POWER": {
              "minV": 6,
              "maxV": 36,
              "maxP": 6
            }
          }
        }
      ]
    },
    {
      "name": "USB-C",
      "connectorId": "USBC_f",
      "subinterfaceTypes": [
        {
          "name": "",
          "direction": "IN",
          "pinout": [],
          "compatibleSignalTypes": ["USB_2"],
          "addInfo": {}
        }
      ]
    },
    {
      "name": "SDI IN 1",
      "connectorId": "BNC_f",
      "subinterfaceTypes": [
        {
          "name": "",
          "direction": "IN",
          "pinout": [],
          "compatibleSignalTypes": ["SDI_SD_CU", "SDI_HD_CU", "SDI_3G_CU"],
          "addInfo": {}
        }
      ]
    },
    {
      "name": "SDI IN 2",
      "connectorId": "BNC_f",
      "subinterfaceTypes": [
        {
          "name": "",
          "direction": "IN",
          "pinout": [],
          "compatibleSignalTypes": ["SDI_SD_CU", "SDI_HD_CU", "SDI_3G_CU"],
          "addInfo": {}
        }
      ]
    },
    {
      "name": "SDI IN 3",
      "connectorId": "BNC_f",
      "subinterfaceTypes": [
        {
          "name": "",
          "direction": "IN",
          "pinout": [],
          "compatibleSignalTypes": ["SDI_SD_CU", "SDI_HD_CU", "SDI_3G_CU"],
          "addInfo": {}
        }
      ]
    },
    {
      "name": "SDI IN 4",
      "connectorId": "BNC_f",
      "subinterfaceTypes": [
        {
          "name": "",
          "direction": "IN",
          "pinout": [],
          "compatibleSignalTypes": ["SDI_SD_CU", "SDI_HD_CU", "SDI_3G_CU"],
          "addInfo": {}
        }
      ]
    },
    {
      "name": "SDI OUT",
      "connectorId": "BNC_f",
      "subinterfaceTypes": [
        {
          "name": "",
          "direction": "OUT",
          "pinout": [],
          "compatibleSignalTypes": ["SDI_HD_CU", "SDI_3G_CU"],
          "addInfo": {}
        }
      ]
    },
    {
      "name": "HDMI OUT",
      "connectorId": "HDMI_A_f",
      "subinterfaceTypes": [
        {
          "name": "",
          "direction": "OUT",
          "pinout": [],
          "compatibleSignalTypes": ["HDMI"],
          "addInfo": {}
        }
      ]
    }
  ],
  "moduleSlotTypes": []
}

=== jan-ldwg/site_manager_templates/v1/deviceTypes/lawo/lawo-edge-dc.json
{
  "id": "lawo-edge-dc",
  "version": "1.0",
  "name": ".edge (DC)",
  "manufacturerId": "lawo",
  "orderCode": ".edge_frame+dc",
  "sku": "A00/20",
  "gtin": null,
  "climateLoad": 700,
  "weight": 8000,
  "width": 483,
  "height": 89,
  "depth": 412,
  "rackType": "19INCH",
  "rackHeight": 2,
  "rackDepth": 412,
  "portTypes": [
    {
      "name": "[PSU 1]",
      "connectorId": "SCREW_M5_m",
      "subinterfaceTypes": [
        {
          "name": "",
          "direction": "IN",
          "pinout": [],
          "compatibleSignalTypes": ["DC_POWER"],
          "addInfo": {
            "DC_POWER": {
              "minV": 48,
              "maxV": 60,
              "maxP": 700
            }
          }
        }
      ]
    },
    {
      "name": "[PSU 2]",
      "connectorId": "SCREW_M5_m",
      "subinterfaceTypes": [
        {
          "name": "",
          "direction": "IN",
          "pinout": [],
          "compatibleSignalTypes": ["DC_POWER"],
          "addInfo": {
            "DC_POWER": {
              "minV": 48,
              "maxV": 60,
              "maxP": 700
            }
          }
        }
      ]
    },
    {
      "name": "[⏚]",
      "connectorId": "SCREW_M5_m",
      "subinterfaceTypes": [
        {
          "name": "",
          "direction": "IN",
          "pinout": [],
          "compatibleSignalTypes": ["GND"],
          "addInfo": {}
        }
      ]
    }
  ],
  "moduleSlotTypes": [
    {
      "name": "Slot 1",
      "canSpan": false,
      "compatibleModuleSlotFormFactors": [],
      "compatibleModuleTypes": ["lawo-edge-gateway"],
      "incompatibleModuleTypes": []
    },
    {
      "name": "Slot 2",
      "canSpan": false,
      "compatibleModuleSlotFormFactors": [],
      "compatibleModuleTypes": ["lawo-edge-gateway"],
      "incompatibleModuleTypes": []
    },
    {
      "name": "Slot 3",
      "canSpan": false,
      "compatibleModuleSlotFormFactors": [],
      "compatibleModuleTypes": ["lawo-edge-gateway"],
      "incompatibleModuleTypes": []
    },
    {
      "name": "Slot 4",
      "canSpan": false,
      "compatibleModuleSlotFormFactors": [],
      "compatibleModuleTypes": ["lawo-edge-gateway"],
      "incompatibleModuleTypes": []
    }
  ]
}

=== jan-ldwg/site_manager_templates/v1/deviceTypes/blackmagic/blackmagic-mini-converter-sdi-to-hdmi-6g.json
{
  "id": "blackmagic-mini-converter-sdi-to-hdmi-6g",
  "version": "1.0",
  "name": "Mini Converter SDI to HDMI 6G",
  "manufacturerId": "blackmagic",
  "orderCode": null,
  "sku": null,
  "gtin": null,
  "climateLoad": 6,
  "weight": 257,
  "width": 115,
  "height": 23,
  "depth": 93,
  "rackType": "NONE",
  "rackHeight": 0,
  "rackDepth": 0,
  "portTypes": [
    {
      "name": "POWER +12V",
      "connectorId": "BARREL_XX_f",
      "subinterfaceTypes": [
        {
          "name": "",
          "direction": "IN",
          "pinout": [],
          "compatibleSignalTypes": ["DC_POWER"],
          "addInfo": {
            "DC_POWER": {
              "minV": 12,
              "maxV": 18,
              "maxP": 6
            }
          }
        }
      ]
    },
    {
      "name": "[USB]",
      "connectorId": "USB2.0B_MINI_f",
      "subinterfaceTypes": [
        {
          "name": "",
          "direction": "IN",
          "pinout": [],
          "compatibleSignalTypes": ["USB_2"],
          "addInfo": {}
        }
      ]
    },
    {
      "name": "SDI IN",
      "connectorId": "BNC_f",
      "subinterfaceTypes": [
        {
          "name": "",
          "direction": "IN",
          "pinout": [],
          "compatibleSignalTypes": [
            "SDI_SD_CU",
            "SDI_HD_CU",
            "SDI_3G_CU",
            "SDI_6G_CU"
          ],
          "addInfo": {}
        }
      ]
    },
    {
      "name": "ALT SDI IN",
      "connectorId": "BNC_f",
      "subinterfaceTypes": [
        {
          "name": "",
          "direction": "IN",
          "pinout": [],
          "compatibleSignalTypes": [
            "SDI_SD_CU",
            "SDI_HD_CU",
            "SDI_3G_CU",
            "SDI_6G_CU"
          ],
          "addInfo": {}
        }
      ]
    },
    {
      "name": "SDI OUT",
      "connectorId": "BNC_f",
      "subinterfaceTypes": [
        {
          "name": "",
          "direction": "OUT",
          "pinout": [],
          "compatibleSignalTypes": [
            "SDI_SD_CU",
            "SDI_HD_CU",
            "SDI_3G_CU",
            "SDI_6G_CU"
          ],
          "addInfo": {}
        }
      ]
    },
    {
      "name": "HDMI",
      "connectorId": "HDMI_A_f",
      "subinterfaceTypes": [
        {
          "name": "",
          "direction": "OUT",
          "pinout": [],
          "compatibleSignalTypes": ["HDMI"],
          "addInfo": {}
        }
      ]
    },
    {
      "name": "L - ANALOG or AES/EBU",
      "connectorId": "TRS_635_f",
      "subinterfaceTypes": [
        {
          "name": "",
          "direction": "OUT",
          "pinout": [],
          "compatibleSignalTypes": ["AUDIO_BAL_ANA", "AES3"],
          "addInfo": {}
        }
      ]
    },
    {
      "name": "R - ANALOG",
      "connectorId": "TRS_635_f",
      "subinterfaceTypes": [
        {
          "name": "",
          "direction": "OUT",
          "pinout": [],
          "compatibleSignalTypes": ["AUDIO_BAL_ANA"],
          "addInfo": {}
        }
      ]
    }
  ],
  "moduleSlotTypes": []
}

=== jan-ldwg/site_manager_templates/v1/deviceTypes/genelec/genelec-8040bpm.json
{
    "id": "genelec-8040bpm",
    "version": "1.0",
    "name": "8040B",
    "manufacturerId": "genelec",
    "orderCode": "8040BPM",
    "sku": null,
    "gtin": null,
    "climateLoad": 110,
    "weight": 9400,
    "width": 237,
    "height": 350,
    "depth": 223,
    "rackType": "NONE",
    "rackHeight": 0,
    "rackDepth": 0,
    "portTypes": [
        {
            "name": "MAINS INPUT",
            "connectorId": "C14_3p_m",
            "subinterfaceTypes": [
                {
                    "name": "",
                    "direction": "IN",
                    "pinout": [],
                    "compatibleSignalTypes": [
                        "AC_POWER_PE"
                    ],
                    "addInfo": {
                        "AC_POWER_PE": {
                            "minF": 50,
                            "maxF": 60,
                            "minV": 100,
                            "maxV": 240,
                            "maxP": 110
                        }
                    }
                }
            ]
        },
        {
            "name": "[Analog In]",
            "connectorId": "XLR3p_f",
            "subinterfaceTypes": [
                {
                    "name": "",
                    "direction": "IN",
                    "pinout": [],
                    "compatibleSignalTypes": [
                        "AUDIO_BAL_ANA"
                    ],
                    "addInfo": {}
                }
            ]
        }
    ],
    "moduleSlotTypes": []
}

=== jan-ldwg/site_manager_templates/v1/deviceTypes/genelec/genelec-8010aw.json
{
    "id": "genelec-8010aw",
    "version": "1.0",
    "name": "8010A",
    "manufacturerId": "genelec",
    "orderCode": "8010AW",
    "sku": null,
    "gtin": null,
    "climateLoad": 30,
    "weight": 1500,
    "width": 121,
    "height": 181,
    "depth": 115,
    "rackType": "NONE",
    "rackHeight": 0,
    "rackDepth": 0,
    "portTypes": [
        {
            "name": "MAINS INPUT",
            "connectorId": "C8_2p_m",
            "subinterfaceTypes": [
                {
                    "name": "",
                    "direction": "IN",
                    "pinout": [],
                    "compatibleSignalTypes": [
                        "AC_POWER"
                    ],
                    "addInfo": {
                        "AC_POWER": {
                            "minF": 50,
                            "maxF": 60,
                            "minV": 100,
                            "maxV": 200,
                            "maxP": 30
                        }
                    }
                }
            ]
        },
        {
            "name": "[Analog In]",
            "connectorId": "XLR3p_f",
            "subinterfaceTypes": [
                {
                    "name": "",
                    "direction": "IN",
                    "pinout": [],
                    "compatibleSignalTypes": [
                        "AUDIO_BAL_ANA"
                    ],
                    "addInfo": {}
                }
            ]
        }
    ],
    "moduleSlotTypes": []
}

=== jan-ldwg/site_manager_templates/v1/deviceTypes/genelec/genelec-8030cm.json
{
    "id": "genelec-8030cm",
    "version": "1.0",
    "name": "8030C",
    "manufacturerId": "genelec",
    "orderCode": "8030CM",
    "sku": null,
    "gtin": null,
    "climateLoad": 60,
    "weight": 5000,
    "width": 189,
    "height": 285,
    "depth": 178,
    "rackType": "NONE",
    "rackHeight": 0,
    "rackDepth": 0,
    "portTypes": [
        {
            "name": "MAINS INPUT",
            "connectorId": "C14_3p_m",
            "subinterfaceTypes": [
                {
                    "name": "",
                    "direction": "IN",
                    "pinout": [],
                    "compatibleSignalTypes": [
                        "AC_POWER_PE"
                    ],
                    "addInfo": {
                        "AC_POWER_PE": {
                            "minF": 50,
                            "maxF": 60,
                            "minV": 100,
                            "maxV": 240,
                            "maxP": 60
                        }
                    }
                }
            ]
        },
        {
            "name": "ANALOG IN",
            "connectorId": "XLR3p_f",
            "subinterfaceTypes": [
                {
                    "name": "",
                    "direction": "IN",
                    "pinout": [],
                    "compatibleSignalTypes": [
                        "AUDIO_BAL_ANA"
                    ],
                    "addInfo": {}
                }
            ]
        }
    ],
    "moduleSlotTypes": []
}

=== jan-ldwg/site_manager_templates/v1/deviceTypes/lawo/lawo-edge-ac.json
{
  "id": "lawo-edge-ac",
  "version": "1.0",
  "name": ".edge (AC)",
  "manufacturerId": "lawo",
  "orderCode": ".edge_frame+ac",
  "sku": "A00/10",
  "gtin": null,
  "climateLoad": 700,
  "weight": 8000,
  "width": 483,
  "height": 89,
  "depth": 412,
  "rackType": "19INCH",
  "rackHeight": 2,
  "rackDepth": 412,
  "portTypes": [
    {
      "name": "[PSU 1]",
      "connectorId": "C14_3p_m",
      "subinterfaceTypes": [
        {
          "name": "",
          "direction": "IN",
          "pinout": [],
          "compatibleSignalTypes": ["AC_POWER_PE"],
          "addInfo": {
            "AC_POWER_PE": {
              "minF": 50,
              "maxF": 60,
              "minV": 100,
              "maxV": 240,
              "maxP": 700
            }
          }
        }
      ]
    },
    {
      "name": "[PSU 2]",
      "connectorId": "C14_3p_m",
      "subinterfaceTypes": [
        {
          "name": "",
          "direction": "IN",
          "pinout": [],
          "compatibleSignalTypes": ["AC_POWER_PE"],
          "addInfo": {
            "AC_POWER_PE": {
              "minF": 50,
              "maxF": 60,
              "minV": 100,
              "maxV": 240,
              "maxP": 700
            }
          }
        }
      ]
    },
    {
      "name": "[⏚]",
      "connectorId": "SCREW_M5_m",
      "subinterfaceTypes": [
        {
          "name": "",
          "direction": "IN",
          "pinout": [],
          "compatibleSignalTypes": ["GND"],
          "addInfo": {}
        }
      ]
    }
  ],
  "moduleSlotTypes": [
    {
      "name": "Slot 1",
      "canSpan": false,
      "compatibleModuleSlotFormFactors": [],
      "compatibleModuleTypes": ["lawo-edge-gateway"],
      "incompatibleModuleTypes": []
    },
    {
      "name": "Slot 2",
      "canSpan": false,
      "compatibleModuleSlotFormFactors": [],
      "compatibleModuleTypes": ["lawo-edge-gateway"],
      "incompatibleModuleTypes": []
    },
    {
      "name": "Slot 3",
      "canSpan": false,
      "compatibleModuleSlotFormFactors": [],
      "compatibleModuleTypes": ["lawo-edge-gateway"],
      "incompatibleModuleTypes": []
    },
    {
      "name": "Slot 4",
      "canSpan": false,
      "compatibleModuleSlotFormFactors": [],
      "compatibleModuleTypes": ["lawo-edge-gateway"],
      "incompatibleModuleTypes": []
    }
  ]
}
