=== jan-ldwg/site_manager_templates/v1/schemas/deviceType.schema.json
{
  "$schema": "https://json-schema.org/draft/2020-12/schema",
  "title": "deviceType",
  "description": "JSON document describing a new deviceType",
  "type": "object",
  "required": ["version", "id", "name", "manufacturerId", "rackType"],
  "additionalProperties": false,
  "properties": {
    "version": {
      "description": "Version number of the template. Minor version must be increased with every change. Major version must only be changed when targeting a different API version.",
      "type": "string",
      "pattern": "^\\d{1,2}\\.\\d{1,2}$"
    },
    "id": {
      "description": "Id of the device type. Consists of id of manufacturer followed by id of device type. See documentation for rules.",
      "type": "string",
      "pattern": "^(?=.{1,48}$)(?!.*--)[a-z](?:[a-z-]{0,14}[a-z])?-[a-z0-9](?:[a-z0-9-]*[a-z0-9])?$",
      "maxLength": 48
    },
    "name": {
      "description": "Name of the device as given by manufacturer",
      "type": "string",
      "maxLength": 256
    },
    "manufacturerId": {
      "description": "Id of the manufacturer of the device type.",
      "type": "string",
      "pattern": "^(?!.*--)[a-z](?:[a-z-]{0,14}[a-z])$",
      "maxLength": 16
    },
    "orderCode": {
      "description": "Order code for the device type as used by the manufacturer.",
      "type": ["string", "null"]
    },
    "sku": {
      "description": "SKU for the device type as used by the manufacturer.",
      "type": ["string", "null"]
    },
    "gtin": {
      "description": "GTIN for the device type as used by the manufacturer.",
      "type": ["string", "null"],
      "maxLength": 14
    },
    "climateLoad": {
      "description": "The maximum heat dissipation of the device type in watt.",
      "type": ["integer", "null"],
      "minimum": 0
    },
    "weight": {
      "description": "Weigth of the device type in gram.",
      "type": ["integer", "null"],
      "minimum": 0
    },
    "width": {
      "description": "Width of the device type in millimeter.",
      "type": ["integer", "null"],
      "minimum": 0
    },
    "height": {
      "description": "Height of the device type in millimeter.",
      "type": ["integer", "null"],
      "minimum": 0
    },
    "depth": {
      "description": "Depth of the device type in millimeter.",
      "type": ["integer", "null"],
      "minimum": 0
    },
    "rackType": {
      "description": "The type of rack the device can be mounted in.",
      "enum": ["19INCH", "NONE"]
    },
    "rackHeight": {
      "description": "The height the device occupies inside a rack in units of that rack type.",
      "type": "integer"
    },
    "rackDepth": {
      "description": "The distance between the mounting plane of the rack and the rear most potrusion of the device in mm.",
      "type": "integer",
      "minimum": 0
    },
    "portTypes": {
      "description": "List of all types of ports on the device type.",
      "type": "array",
      "items": {
        "type": "object",
        "required": ["name", "connectorId", "subinterfaceTypes"],
        "additionalProperties": false,
        "properties": {
          "name": {
            "description": "Name of the port, as printed on the device.",
            "type": "string"
          },
          "connectorId": {
            "description": "Id of the connector.",
            "type": "string",
            "pattern": "^[A-Za-z0-9](?:[A-Za-z0-9]|[_.](?=[A-Za-z0-9]))*_(?:f|m|h)$"
          },
          "subinterfaceTypes": {
            "description": "List of all subinterfaceTypes included in the portType",
            "type": "array",
            "items": {
              "type": "object",
              "required": ["name", "direction", "compatibleSignalTypes"],
              "additionalProperties": false,
              "properties": {
                "name": {
                  "description": "The name of the subinterfaceType. Left null if only one subinterface exists on the port. Else a descriptive name, like Ch. 1, GPI IN 3, etc.",
                  "type": ["string", "null"]
                },
                "direction": {
                  "description": "Direction of the subinterFaceType. See documentation for explainations of the possible values.",
                  "enum": [
                    "IN",
                    "OUT",
                    "INOUT",
                    "BIDI",
                    "UP",
                    "DOWN",
                    "FRONT",
                    "REAR"
                  ]
                },
                "compatibleSignalTypes": {
                  "description": "List of signal types that are compatible with this port.",
                  "type": "array",
                  "items": {
                    "type": "string",
                    "pattern": "^(?!.*--)(?:[a-z](?:[a-z-]{0,14}[a-z])?_)?[A-Z0-9]+(?:_[A-Z0-9]+)*$"
                  },
                  "uniqueItems": true
                },
                "pinout": {
                  "description": "An array describing the pins asscociated with the subinterface.",
                  "type": ["array", "null"],
                  "items": {
                    "type": "object",
                    "additionalProperties": false,
                    "properties": {
                      "pin": {
                        "description": "A human readable identification of the pin, e.g. its number or center/shield for BNC.",
                        "type": "string"
                      },
                      "signal": {
                        "description": "The signal present on that pin. This is not the signalType, but something more basic like positive, negative, GND, etc.",
                        "type": "string"
                      }
                    }
                  }
                },
                "addInfo": {
                  "description": "An object that contains additional information, depending on the signalType",
                  "type": ["object", "null"],
                  "additionalProperties": false,
                  "properties": {
                    "AC_POWER": {
                      "type": "object",
                      "additionalProperties": false,
                      "properties": {
                        "minV": {
                          "description": "Minimum acceptable voltage of a power input or output",
                          "type": "number"
                        },
                        "maxV": {
                          "description": "Maximum acceptable voltage of a power input or output",
                          "type": "number"
                        },
                        "minF": {
                          "description": "Minimum acceptable frequency of a power input or output",
                          "type": "number"
                        },
                        "maxF": {
                          "description": "Maximum acceptable frequency of a power input or output",
                          "type": "number"
                        },
                        "maxP": {
                          "description": "Maximum acceptable power of a power input or output",
                          "type": "number"
                        }
                      }
                    },
                    "AC_POWER_PE": {
                      "type": "object",
                      "additionalProperties": false,
                      "properties": {
                        "minV": {
                          "description": "Minimum acceptable voltage of a power input or output",
                          "type": "number"
                        },
                        "maxV": {
                          "description": "Maximum acceptable voltage of a power input or output",
                          "type": "number"
                        },
                        "minF": {
                          "description": "Minimum acceptable frequency of a power input or output",
                          "type": "number"
                        },
                        "maxF": {
                          "description": "Maximum acceptable frequency of a power input or output",
                          "type": "number"
                        },
                        "maxP": {
                          "description": "Maximum acceptable power of a power input or output",
                          "type": "number"
                        }
                      }
                    },
                    "THREE_PHASE_POWER": {
                      "type": "object",
                      "additionalProperties": false,
                      "properties": {
                        "minV": {
                          "description": "Minimum acceptable voltage of a power input or output",
                          "type": "number"
                        },
                        "maxV": {
                          "description": "Maximum acceptable voltage of a power input or output",
                          "type": "number"
                        },
                        "minF": {
                          "description": "Minimum acceptable frequency of a power input or output",
                          "type": "number"
                        },
                        "maxF": {
                          "description": "Maximum acceptable frequency of a power input or output",
                          "type": "number"
                        },
                        "maxP": {
                          "description": "Maximum acceptable power of a power input or output",
                          "type": "number"
                        }
                      }
                    },
                    "DC_POWER": {
                      "type": "object",
                      "additionalProperties": false,
                      "properties": {
                        "minV": {
                          "description": "Minimum acceptable voltage of a power input or output",
                          "type": "number"
                        },
                        "maxV": {
                          "description": "Maximum acceptable voltage of a power input or output",
                          "type": "number"
                        },
                        "maxP": {
                          "description": "Maximum acceptable power of a power input or output",
                          "type": "number"
                        }
                      }
                    },
                    "POE": {
                      "oneOf": [
                        {
                          "type": "object",
                          "additionalProperties": false,
                          "required": ["role"],
                          "properties": { "role": { "const": "NONE" } }
                        },
                        {
                          "type": "object",
                          "additionalProperties": false,
                          "required": ["role", "maxP"],
                          "properties": {
                            "role": { "const": "PSE" },
                            "maxP": {
                              "type": "number",
                              "exclusiveMinimum": 0
                            }
                          }
                        },
                        {
                          "type": "object",
                          "additionalProperties": false,
                          "required": ["role", "maxP", "required"],
                          "properties": {
                            "role": { "const": "PD" },
                            "maxP": {
                              "type": "number",
                              "exclusiveMinimum": 0
                            },
                            "required": { "type": "boolean" }
                          }
                        }
                      ]
                    }
                  }
                }
              }
            }
          }
        }
      }
    },
    "moduleSlotTypes": {
      "description": "List of all types of module slots on the device type.",
      "type": "array",
      "items": {
        "type": "object",
        "required": [
          "name",
          "compatibleModuleSlotFormFactors",
          "compatibleModuleTypes",
          "incompatibleModuleTypes"
        ],
        "additionalProperties": false,
        "properties": {
          "name": {
            "description": "Name of the module slot, as labeled on the device.",
            "type": "string"
          },
          "canSpan": {
            "description": "Indicates wether a module can span into the next slot",
            "type": "boolean"
          },
          "compatibleModuleSlotFormFactors": {
            "description": "List of module slot factors that can physically fit into the slot.",
            "type": "array",
            "uniqueItems": true,
            "items": {
              "type": "string",
              "pattern": "^[a-z0-9]+(?:-[a-z0-9]+)*$"
            }
          },
          "compatibleModuleTypes": {
            "description": "List of module types that are guranteed by the manufacturer to work in this slot.",
            "type": "array",
            "uniqueItems": true,
            "items": {
              "type": "string",
              "pattern": "^(?=.{1,48}$)(?!.*--)[a-z](?:[a-z-]{0,14}[a-z])?-[a-z0-9](?:[a-z0-9-]*[a-z0-9])?$"
            }
          },
          "incompatibleModuleTypes": {
            "description": "List of module types that are guranteed by the manufacturer not work in this module slot.",
            "type": "array",
            "uniqueItems": true,
            "items": {
              "type": "string",
              "pattern": "^(?=.{1,48}$)(?!.*--)[a-z](?:[a-z-]{0,14}[a-z])?-[a-z0-9](?:[a-z0-9-]*[a-z0-9])?$"
            }
          }
        }
      }
    }
  }
}

=== jan-ldwg/site_manager_templates/v1/deviceTypes/blackmagic/blackmagic-micro-converter-bidi-sdi-hdmi-3g.json
{
  "id": "blackmagic-micro-converter-bidi-sdi-hdmi-3g",
  "version": "1.0",
  "name": "Micro Converter BiDirectional SDI/HDMI 3G",
  "manufacturerId": "blackmagic",
  "orderCode": null,
  "sku": null,
  "gtin": null,
  "climateLoad": 3,
  "weight": 174,
  "width": 81,
  "height": 25,
  "depth": 59,
  "rackType": "NONE",
  "rackHeight": 0,
  "rackDepth": 0,
  "portTypes": [
    {
      "name": "USB POWER",
      "connectorId": "USBC_f",
      "subinterfaceTypes": [
        {
          "name": "",
          "direction": "IN",
          "pinout": [],
          "compatibleSignalTypes": ["USB_2"],
          "addInfo": {}
        }
      ]
    },
    {
      "name": "HDMI IN",
      "connectorId": "HDMI_A_f",
      "subinterfaceTypes": [
        {
          "name": "",
          "direction": "IN",
          "pinout": [],
          "compatibleSignalTypes": ["HDMI"],
          "addInfo": {}
        }
      ]
    },
    {
      "name": "HDMI OUT",
      "connectorId": "HDMI_A_f",
      "subinterfaceTypes": [
        {
          "name": "",
          "direction": "OUT",
          "pinout": [],
          "compatibleSignalTypes": ["HDMI"],
          "addInfo": {}
        }
      ]
    },
    {
      "name": "SDI IN",
      "connectorId": "BNC_f",
      "subinterfaceTypes": [
        {
          "name": "",
          "direction": "IN",
          "pinout": [],
          "compatibleSignalTypes": ["SDI_SD_CU", "SDI_HD_CU", "SDI_3G_CU"],
          "addInfo": {}
        }
      ]
    },
    {
      "name": "SDI OUT",
      "connectorId": "BNC_f",
      "subinterfaceTypes": [
        {
          "name": "",
          "direction": "OUT",
          "pinout": [],
          "compatibleSignalTypes": ["SDI_SD_CU", "SDI_HD_CU", "SDI_3G_CU"],
          "addInfo": {}
        }
      ]
    }
  ],
  "moduleSlotTypes": []
}

=== jan-ldwg/site_manager_templates/v1/deviceTypes/blackmagic/blackmagic-mini-converter-audio-to-sdi.json
{
  "id": "blackmagic-mini-converter-audio-to-sdi",
  "version": "1.0",
  "name": "Mini Converter Audio to SDI",
  "manufacturerId": "blackmagic",
  "orderCode": null,
  "sku": null,
  "gtin": null,
  "climateLoad": 9,
  "weight": 215,
  "width": 115,
  "height": 23,
  "depth": 93,
  "rackType": "NONE",
  "rackHeight": 0,
  "rackDepth": 0,
  "portTypes": [
    {
      "name": "POWER +12V",
      "connectorId": "BARREL_XX_f",
      "subinterfaceTypes": [
        {
          "name": "",
          "direction": "IN",
          "pinout": [],
          "compatibleSignalTypes": ["DC_POWER"],
          "addInfo": {
            "DC_POWER": {
              "minV": 12,
              "maxV": 12,
              "maxP": 9
            }
          }
        }
      ]
    },
    {
      "name": "[USB]",
      "connectorId": "USB2.0B_MINI_f",
      "subinterfaceTypes": [
        {
          "name": "",
          "direction": "IN",
          "pinout": [],
          "compatibleSignalTypes": ["USB_2"],
          "addInfo": {}
        }
      ]
    },
    {
      "name": "SDI IN",
      "connectorId": "BNC_f",
      "subinterfaceTypes": [
        {
          "name": "",
          "direction": "IN",
          "pinout": [],
          "compatibleSignalTypes": ["SDI_SD_CU", "SDI_HD_CU", "SDI_3G_CU"],
          "addInfo": {}
        }
      ]
    },
    {
      "name": "ALT SDI IN",
      "connectorId": "BNC_f",
      "subinterfaceTypes": [
        {
          "name": "",
          "direction": "IN",
          "pinout": [],
          "compatibleSignalTypes": ["SDI_SD_CU", "SDI_HD_CU", "SDI_3G_CU"],
          "addInfo": {}
        }
      ]
    },
    {
      "name": "SDI OUT",
      "connectorId": "BNC_f",
      "subinterfaceTypes": [
        {
          "name": "",
          "direction": "OUT",
          "pinout": [],
          "compatibleSignalTypes": ["SDI_SD_CU", "SDI_HD_CU", "SDI_3G_CU"],
          "addInfo": {}
        }
      ]
    },
    {
      "name": "CH 1 ANALOG or CH 1&2 AES/EBU",
      "connectorId": "TRS_635_f",
      "subinterfaceTypes": [
        {
          "name": "",
          "direction": "IN",
          "pinout": [],
          "compatibleSignalTypes": ["AUDIO_BAL_ANA", "AES3"],
          "addInfo": {}
        }
      ]
    },
    {
      "name": "CH 2 ANALOG or CH 3&4 AES/EBU",
      "connectorId": "TRS_635_f",
      "subinterfaceTypes": [
        {
          "name": "",
          "direction": "IN",
          "pinout": [],
          "compatibleSignalTypes": ["AUDIO_BAL_ANA", "AES3"],
          "addInfo": {}
        }
      ]
    },
    {
      "name": "CH 3 ANALOG or CH 5&6 AES/EBU",
      "connectorId": "TRS_635_f",
      "subinterfaceTypes": [
        {
          "name": "",
          "direction": "IN",
          "pinout": [],
          "compatibleSignalTypes": ["AUDIO_BAL_ANA", "AES3"],
          "addInfo": {}
        }
      ]
    },
    {
      "name": "CH 4 ANALOG or CH 7&8 AES/EBU",
      "connectorId": "TRS_635_f",
      "subinterfaceTypes": [
        {
          "name": "",
          "direction": "IN",
          "pinout": [],
          "compatibleSignalTypes": ["AUDIO_BAL_ANA", "AES3"],
          "addInfo": {}
        }
      ]
    }
  ],
  "moduleSlotTypes": []
}

=== jan-ldwg/site_manager_templates/v1/deviceTypes/blackmagic/blackmagic-mini-converter-analog-to-sdi.json
{
  "id": "blackmagic-mini-converter-analog-to-sdi",
  "version": "1.0",
  "name": "Mini Converter Analog to SDI",
  "manufacturerId": "blackmagic",
  "orderCode": null,
  "sku": null,
  "gtin": null,
  "climateLoad": 7,
  "weight": 236,
  "width": 124,
  "height": 23,
  "depth": 93,
  "rackType": "NONE",
  "rackHeight": 0,
  "rackDepth": 0,
  "portTypes": [
    {
      "name": "POWER +12V",
      "connectorId": "BARREL_XX_f",
      "subinterfaceTypes": [
        {
          "name": "",
          "direction": "IN",
          "pinout": [],
          "compatibleSignalTypes": ["DC_POWER"],
          "addInfo": {
            "DC_POWER": {
              "minV": 12,
              "maxV": 31,
              "maxP": 7
            }
          }
        }
      ]
    },
    {
      "name": "[USB]",
      "connectorId": "USB2.0B_MINI_f",
      "subinterfaceTypes": [
        {
          "name": "",
          "direction": "IN",
          "pinout": [],
          "compatibleSignalTypes": ["USB_2"],
          "addInfo": {}
        }
      ]
    },
    {
      "name": "SDI OUT",
      "connectorId": "BNC_f",
      "subinterfaceTypes": [
        {
          "name": "",
          "direction": "OUT",
          "pinout": [],
          "compatibleSignalTypes": ["SDI_SD_CU", "SDI_HD_CU"],
          "addInfo": {}
        }
      ]
    },
    {
      "name": "SDI OUT",
      "connectorId": "BNC_f",
      "subinterfaceTypes": [
        {
          "name": "",
          "direction": "OUT",
          "pinout": [],
          "compatibleSignalTypes": ["SDI_SD_CU", "SDI_HD_CU"],
          "addInfo": {}
        }
      ]
    },
    {
      "name": "Y or NTSC/PAL",
      "connectorId": "BNC_f",
      "subinterfaceTypes": [
        {
          "name": "",
          "direction": "IN",
          "pinout": [],
          "compatibleSignalTypes": ["Y", "CVBS"],
          "addInfo": {}
        }
      ]
    },
    {
      "name": "B-Y or S-VIDEO Y",
      "connectorId": "BNC_f",
      "subinterfaceTypes": [
        {
          "name": "",
          "direction": "IN",
          "pinout": [],
          "compatibleSignalTypes": ["PB", "S_VIDEO_Y"],
          "addInfo": {}
        }
      ]
    },
    {
      "name": "R-Y or S-VIDEO C",
      "connectorId": "BNC_f",
      "subinterfaceTypes": [
        {
          "name": "",
          "direction": "IN",
          "pinout": [],
          "compatibleSignalTypes": ["PR", "S_VIDEO_C"],
          "addInfo": {}
        }
      ]
    },
    {
      "name": "L - ANALOG or AES/EBU",
      "connectorId": "TRS_635_f",
      "subinterfaceTypes": [
        {
          "name": "",
          "direction": "IN",
          "pinout": [],
          "compatibleSignalTypes": ["AUDIO_BAL_ANA", "AES3"],
          "addInfo": {}
        }
      ]
    },
    {
      "name": "R - ANALOG",
      "connectorId": "TRS_635_f",
      "subinterfaceTypes": [
        {
          "name": "",
          "direction": "IN",
          "pinout": [],
          "compatibleSignalTypes": ["AUDIO_BAL_ANA"],
          "addInfo": {}
        }
      ]
    }
  ],
  "moduleSlotTypes": []
}

=== jan-ldwg/site_manager_templates/v1/deviceTypes/riedel/riedel-esp-1216hl.json
{
  "id": "riedel-esp-1216hl",
  "version": "1.0",
  "name": "ESP-1216HL",
  "manufacturerId": "riedel",
  "orderCode": null,
  "sku": "1220700",
  "gtin": null,
  "climateLoad": 15,
  "weight": 2100,
  "width": 483,
  "height": 44,
  "depth": 131,
  "rackType": "19INCH",
  "rackHeight": 1,
  "rackDepth": 102,
  "portTypes": [
    {
      "name": "INPUT",
      "connectorId": "C14_3p_m",
      "subinterfaceTypes": [
        {
          "name": "",
          "direction": "IN",
          "pinout": [],
          "compatibleSignalTypes": ["AC_POWER_PE"],
          "addInfo": {
            "AC_POWER_PE": {
              "minF": 50,
              "maxF": 60,
              "minV": 100,
              "maxV": 240,
              "maxP": 15
            }
          }
        }
      ]
    },
    {
      "name": "EXP I/O",
      "connectorId": "RJ45_f",
      "subinterfaceTypes": [
        {
          "name": "",
          "direction": "IN",
          "pinout": [],
          "compatibleSignalTypes": ["riedel_EXPANSION"],
          "addInfo": {}
        }
      ]
    },
    {
      "name": "EXP I/O",
      "connectorId": "RJ45_f",
      "subinterfaceTypes": [
        {
          "name": "",
          "direction": "OUT",
          "pinout": [],
          "compatibleSignalTypes": ["riedel_EXPANSION"],
          "addInfo": {}
        }
      ]
    }
  ],
  "moduleSlotTypes": []
}

=== jan-ldwg/site_manager_templates/v1/deviceTypes/blackmagic/blackmagic-micro-converter-sdi-to-hdmi-3g.json
{
  "id": "blackmagic-micro-converter-sdi-to-hdmi-3g",
  "version": "1.0",
  "name": "Micro Converter SDI to HDMI 3G",
  "manufacturerId": "blackmagic",
  "orderCode": null,
  "sku": null,
  "gtin": null,
  "climateLoad": 2,
  "weight": 150,
  "width": 80,
  "height": 25,
  "depth": 46,
  "rackType": "NONE",
  "rackHeight": 0,
  "rackDepth": 0,
  "portTypes": [
    {
      "name": "USB POWER",
      "connectorId": "USBC_f",
      "subinterfaceTypes": [
        {
          "name": "",
          "direction": "IN",
          "pinout": [],
          "compatibleSignalTypes": ["USB_2"],
          "addInfo": {}
        }
      ]
    },
    {
      "name": "SDI IN",
      "connectorId": "BNC_f",
      "subinterfaceTypes": [
        {
          "name": "",
          "direction": "IN",
          "pinout": [],
          "compatibleSignalTypes": ["SDI_SD_CU", "SDI_HD_CU", "SDI_3G_CU"],
          "addInfo": {}
        }
      ]
    },
    {
      "name": "SDI LOOP OUT",
      "connectorId": "BNC_f",
      "subinterfaceTypes": [
        {
          "name": "",
          "direction": "OUT",
          "pinout": [],
          "compatibleSignalTypes": ["SDI_SD_CU", "SDI_HD_CU", "SDI_3G_CU"],
          "addInfo": {}
        }
      ]
    },
    {
      "name": "HDMI OUT",
      "connectorId": "HDMI_A_f",
      "subinterfaceTypes": [
        {
          "name": "",
          "direction": "OUT",
          "pinout": [],
          "compatibleSignalTypes": ["HDMI"],
          "addInfo": {}
        }
      ]
    }
  ],
  "moduleSlotTypes": []
}

=== jan-ldwg/site_manager_templates/v1/deviceTypes/blackmagic/blackmagic-mini-converter-sdi-distribution.json
{
  "id": "blackmagic-mini-converter-sdi-distribution",
  "version": "1.0",
  "name": "Mini Converter SDI Distribution",
  "manufacturerId": "blackmagic",
  "orderCode": null,
  "sku": null,
  "gtin": null,
  "climateLoad": 5,
  "weight": 240,
  "width": 123,
  "height": 23,
  "depth": 93,
  "rackType": "NONE",
  "rackHeight": 0,
  "rackDepth": 0,
  "portTypes": [
    {
      "name": "POWER +12V",
      "connectorId": "BARREL_XX_f",
      "subinterfaceTypes": [
        {
          "name": "",
          "direction": "IN",
          "pinout": [],
          "compatibleSignalTypes": ["DC_POWER"],
          "addInfo": {
            "DC_POWER": {
              "minV": 12,
              "maxV": 31,
              "maxP": 5
            }
          }
        }
      ]
    },
    {
      "name": "SDI IN",
      "connectorId": "BNC_f",
      "subinterfaceTypes": [
        {
          "name": "",
          "direction": "IN",
          "pinout": [],
          "compatibleSignalTypes": [
            "SDI_SD_CU",
            "SDI_HD_CU",
            "SDI_3G_CU",
            "DVB_ASI"
          ],
          "addInfo": {}
        }
      ]
    },
    {
      "name": "SDI OUT",
      "connectorId": "BNC_f",
      "subinterfaceTypes": [
        {
          "name": "",
          "direction": "OUT",
          "pinout": [],
          "compatibleSignalTypes": [
            "SDI_SD_CU",
            "SDI_HD_CU",
            "SDI_3G_CU",
            "DVB_ASI"
          ],
          "addInfo": {}
        }
      ]
    },
    {
      "name": "SDI OUT",
      "connectorId": "BNC_f",
      "subinterfaceTypes": [
        {
          "name": "",
          "direction": "OUT",
          "pinout": [],
          "compatibleSignalTypes": [
            "SDI_SD_CU",
            "SDI_HD_CU",
            "SDI_3G_CU",
            "DVB_ASI"
          ],
          "addInfo": {}
        }
      ]
    },
    {
      "name": "SDI OUT",
      "connectorId": "BNC_f",
      "subinterfaceTypes": [
        {
          "name": "",
          "direction": "OUT",
          "pinout": [],
          "compatibleSignalTypes": [
            "SDI_SD_CU",
            "SDI_HD_CU",
            "SDI_3G_CU",
            "DVB_ASI"
          ],
          "addInfo": {}
        }
      ]
    },
    {
      "name": "SDI OUT",
      "connectorId": "BNC_f",
      "subinterfaceTypes": [
        {
          "name": "",
          "direction": "OUT",
          "pinout": [],
          "compatibleSignalTypes": [
            "SDI_SD_CU",
            "SDI_HD_CU",
            "SDI_3G_CU",
            "DVB_ASI"
          ],
          "addInfo": {}
        }
      ]
    },
    {
      "name": "SDI OUT",
      "connectorId": "BNC_f",
      "subinterfaceTypes": [
        {
          "name": "",
          "direction": "OUT",
          "pinout": [],
          "compatibleSignalTypes": [
            "SDI_SD_CU",
            "SDI_HD_CU",
            "SDI_3G_CU",
            "DVB_ASI"
          ],
          "addInfo": {}
        }
      ]
    },
    {
      "name": "SDI OUT",
      "connectorId": "BNC_f",
      "subinterfaceTypes": [
        {
          "name": "",
          "direction": "OUT",
          "pinout": [],
          "compatibleSignalTypes": [
            "SDI_SD_CU",
            "SDI_HD_CU",
            "SDI_3G_CU",
            "DVB_ASI"
          ],
          "addInfo": {}
        }
      ]
    },
    {
      "name": "SDI OUT",
      "connectorId": "BNC_f",
      "subinterfaceTypes": [
        {
          "name": "",
          "direction": "OUT",
          "pinout": [],
          "compatibleSignalTypes": [
            "SDI_SD_CU",
            "SDI_HD_CU",
            "SDI_3G_CU",
            "DVB_ASI"
          ],
          "addInfo": {}
        }
      ]
    },
    {
      "name": "SDI OUT",
      "connectorId": "BNC_f",
      "subinterfaceTypes": [
        {
          "name": "",
          "direction": "OUT",
          "pinout": [],
          "compatibleSignalTypes": [
            "SDI_SD_CU",
            "SDI_HD_CU",
            "SDI_3G_CU",
            "DVB_ASI"
          ],
          "addInfo": {}
        }
      ]
    }
  ],
  "moduleSlotTypes": []
}
