=== jan-ldwg/site_manager_templates/schemas/devicetype.schema.json
{
  "$schema": "https://json-schema.org/draft/2020-12/schema",
  "title": "devicetype",
  "description": "JSON document describing a new device type",
  "type": "object",
  "properties": {
    "version": {
      "description": "Version number of the template. Minor version must be increased with every change. Major version must only be changed when targeting a different API version.",
      "type": "string",
      "pattern": "^\\d{1,2}\\.\\d{1,2}$"
    },
    "id": {
      "description": "Id of the device type. Consists of id of manufacturer followed by id of device type. See documentation for rules.",
      "type": "string",
      "pattern": "^(?=.{1,48}$)(?!.*--)[a-z](?:[a-z-]{0,14}[a-z])?-[a-z0-9](?:[a-z0-9-]*[a-z0-9])?$",
      "maxLength": 48
    },
    "name": {
      "description": "Name of the device as given by manufacturer",
      "type": "string",
      "maxLength": 256
    },
    "manufacturerId": {
      "description": "Id of the manufacturer of the device type.",
      "type": "string",
      "pattern": "^(?!.*--)[a-z](?:[a-z-]{0,14}[a-z])$",
      "maxLength": 16
    },
    "orderCode": {
      "description": "Order code for the device type as used by the manufacturer.",
      "type": ["string", "null"]
    },
    "orderNumber": {
      "description": "Order number for the device type as used by the manufacturer.",
      "type": ["string", "null"]
    },
    "climateLoad": {
      "description": "The maximum heat dissipation of the device type.",
      "type": ["integer", "null"],
      "minimum": 0
    },
    "rackType": {
      "description": "The type of rack the device can be mounted in.",
      "enum": ["19INCH", "NONE"]
    },
    "rackHeight": {
      "description": "The height the device occupies inside a rack in units of that rack type.",
      "type": "integer"
    },
    "rackDepth": {
      "description": "The distance between the mounting plane of the rack and the rear most potrusion of the device in mm.",
      "type": "integer",
      "minimum": 0
    },
    "portTypes": {
      "description": "List of all types of ports on the device type.",
      "type": "array",
      "items": {
        "type": "object",
        "properties": {
          "name": {
            "description": "Name of the port, as printed on the device.",
            "type": "string"
          },
          "direction": {
            "description": "Direction of the port type. See documentation for explainations of the possible values.",
            "enum": [
              "IN",
              "OUT",
              "INOUT",
              "BIDI",
              "UP",
              "DOWN",
              "FRONT",
              "REAR"
            ]
          },
          "connectorId": {
            "description": "Id of the connector.",
            "type": "string",
            "pattern": "^[A-Za-z0-9](?:[A-Za-z0-9]|[_.](?=[A-Za-z0-9]))*_(?:f|m|h)$"
          },
          "compatibleSignalTypes": {
            "description": "List of signal types that are compatible with this port.",
            "type": "array",
            "items": {
              "type": "string",
              "pattern": "^(?!.*--)(?:[a-z](?:[a-z-]{0,14}[a-z])?_)?[A-Z0-9]+(?:_[A-Z0-9]+)*$"
            },
            "uniqueItems": true
          }
        },
        "required": [
          "name",
          "direction",
          "connectorId",
          "compatibleSignalTypes"
        ],
        "additionalProperties": false
      }
    },
    "moduleSlotTypes": {
      "description": "List of all types of module slots on the device type.",
      "type": "array",
      "items": {
        "type": "object",
        "properties": {
          "name": {
            "description": "Name of the module slot, as labeled on the device.",
            "type": "string"
          },
          "canSpan": {
            "description": "Indicates wether a module can span into the next slot",
            "type": "boolean"
          },
          "compatibleModuleSlotFormFactors": {
            "description": "List of module slot factors that can physically fit into the slot.",
            "type": "array",
            "uniqueItems": true,
            "items": {
              "type": "string",
              "pattern": "^[a-z0-9]+(?:-[a-z0-9]+)*$"
            }
          },
          "compatibleModuleTypes": {
            "description": "List of module types that are guranteed by the manufacturer to work in this slot.",
            "type": "array",
            "uniqueItems": true,
            "items": {
              "type": "string",
              "pattern": "^(?=.{1,48}$)(?!.*--)[a-z](?:[a-z-]{0,14}[a-z])?-[a-z0-9](?:[a-z0-9-]*[a-z0-9])?$"
            }
          },
          "incompatibleModuleTypes": {
            "description": "List of module types that are guranteed by the manufacturer not work in this module slot.",
            "type": "array",
            "uniqueItems": true,
            "items": {
              "type": "string",
              "pattern": "^(?=.{1,48}$)(?!.*--)[a-z](?:[a-z-]{0,14}[a-z])?-[a-z0-9](?:[a-z0-9-]*[a-z0-9])?$"
            }
          }
        },
        "required": [
          "name",
          "compatibleModuleSlotFormFactors",
          "compatibleModuleTypes",
          "incompatibleModuleTypes"
        ],
        "additionalProperties": false
      }
    }
  },
  "required": ["version", "id", "name", "manufacturerId", "rackType"],
  "additionalProperties": false
}

=== jan-ldwg/site_manager_templates/devicetypes/lynx/lynx-r-fr-5018.json
{
  "id": "lynx-r-fr-5018",
  "version": "1.0",
  "name": "R FR 5018",
  "manufacturerId": "lynx",
  "orderCode": "RFR 5018",
  "orderNumber": "4250479327689",
  "climateLoad": 180,
  "rackType": "19INCH",
  "rackHeight": 2,
  "rackDepth": 325,
  "portTypes": [
    {
      "name": "LAN",
      "direction": "DOWN",
      "connectorId": "RJ45_f",
      "compatibleSignalTypes": ["10BASE_T", "100BASE_TX"]
    },
    {
      "name": "SYNC IN",
      "direction": "IN",
      "connectorId": "BNC_f",
      "compatibleSignalTypes": ["BLACK_BURST", "TRI_SYNC"]
    },
    {
      "name": "SYNC OUT",
      "direction": "OUT",
      "connectorId": "BNC_f",
      "compatibleSignalTypes": ["BLACK_BURST", "TRI_SYNC"]
    },
    {
      "name": "GPI Input 1-4",
      "direction": "IN",
      "connectorId": "RJ45_f",
      "compatibleSignalTypes": ["GPIO"]
    },
    {
      "name": "GPI Input 1-4",
      "direction": "IN",
      "connectorId": "RJ45_f",
      "compatibleSignalTypes": ["GPIO"]
    },
    {
      "name": "GPI Input 5-8",
      "direction": "IN",
      "connectorId": "RJ45_f",
      "compatibleSignalTypes": ["GPIO"]
    },
    {
      "name": "GPI Input 5-8",
      "direction": "IN",
      "connectorId": "RJ45_f",
      "compatibleSignalTypes": ["GPIO"]
    },
    {
      "name": "[Alarm]",
      "direction": "INOUT",
      "connectorId": "TERMINAL_generic_10p_f",
      "compatibleSignalTypes": ["GPIO"]
    }
  ],
  "moduleSlotTypes": [
    {
      "name": "Controller",
      "canSpan": false,
      "compatibleModuleSlotFormFactors": [],
      "compatibleModuleTypes": ["lynx-rct-5023g"],
      "incompatibleModuleTypes": []
    },
    {
      "name": "Slot 1",
      "canSpan": true,
      "compatibleModuleSlotFormFactors": [
        "lynx-5000-passive",
        "lynx-5000-active"
      ],
      "compatibleModuleTypes": [],
      "incompatibleModuleTypes": []
    },
    {
      "name": "Slot 2",
      "canSpan": true,
      "compatibleModuleSlotFormFactors": [
        "lynx-5000-passive",
        "lynx-5000-active"
      ],
      "compatibleModuleTypes": [],
      "incompatibleModuleTypes": []
    },
    {
      "name": "Slot 3",
      "canSpan": true,
      "compatibleModuleSlotFormFactors": [
        "lynx-5000-passive",
        "lynx-5000-active"
      ],
      "compatibleModuleTypes": [],
      "incompatibleModuleTypes": []
    },
    {
      "name": "Slot 4",
      "canSpan": true,
      "compatibleModuleSlotFormFactors": [
        "lynx-5000-passive",
        "lynx-5000-active"
      ],
      "compatibleModuleTypes": [],
      "incompatibleModuleTypes": []
    },
    {
      "name": "Slot 5",
      "canSpan": true,
      "compatibleModuleSlotFormFactors": [
        "lynx-5000-passive",
        "lynx-5000-active"
      ],
      "compatibleModuleTypes": [],
      "incompatibleModuleTypes": []
    },
    {
      "name": "Slot 6",
      "canSpan": true,
      "compatibleModuleSlotFormFactors": [
        "lynx-5000-passive",
        "lynx-5000-active"
      ],
      "compatibleModuleTypes": [],
      "incompatibleModuleTypes": []
    },
    {
      "name": "Slot 7",
      "canSpan": true,
      "compatibleModuleSlotFormFactors": [
        "lynx-5000-passive",
        "lynx-5000-active"
      ],
      "compatibleModuleTypes": [],
      "incompatibleModuleTypes": []
    },
    {
      "name": "Slot 8",
      "canSpan": true,
      "compatibleModuleSlotFormFactors": [
        "lynx-5000-passive",
        "lynx-5000-active"
      ],
      "compatibleModuleTypes": [],
      "incompatibleModuleTypes": []
    },
    {
      "name": "Slot 9",
      "canSpan": true,
      "compatibleModuleSlotFormFactors": [
        "lynx-5000-passive",
        "lynx-5000-active"
      ],
      "compatibleModuleTypes": [],
      "incompatibleModuleTypes": []
    },
    {
      "name": "Slot 10",
      "canSpan": false,
      "compatibleModuleSlotFormFactors": [
        "lynx-5000-passive",
        "lynx-5000-active"
      ],
      "compatibleModuleTypes": [],
      "incompatibleModuleTypes": []
    }
  ]
}

=== jan-ldwg/site_manager_templates/devicetypes/brainstorm/brainstorm-dxd-16.json
{
  "version": "1.0",
  "id": "brainstorm-dxd-16",
  "name": "DXD-16",
  "manufacturerId": "brainstorm",
  "orderCode": null,
  "orderNumber": null,
  "climateLoad": 48,
  "rackType": "19INCH",
  "rackHeight": 1,
  "rackDepth": 203,
  "portTypes": [
    {
      "name": "NETWORK 1",
      "direction": "UP",
      "connectorId": "RJ45_f",
      "compatibleSignalTypes": ["1000BASE_T"]
    },
    {
      "name": "NETWORK 2",
      "direction": "UP",
      "connectorId": "RJ45_f",
      "compatibleSignalTypes": ["1000BASE_T"]
    },
    {
      "name": "NETWORK 3",
      "direction": "UP",
      "connectorId": "RJ45_f",
      "compatibleSignalTypes": ["1000BASE_T"]
    },
    {
      "name": "NETWORK 4",
      "direction": "UP",
      "connectorId": "RJ45_f",
      "compatibleSignalTypes": ["1000BASE_T"]
    },
    {
      "name": "RS-232 / GPI/O / TC OUT / 1PPS I/O",
      "direction": "INOUT",
      "connectorId": "DSUB25p_f",
      "compatibleSignalTypes": ["GPIO"]
    },
    {
      "name": "INPUT A",
      "direction": "IN",
      "connectorId": "BNC_f",
      "compatibleSignalTypes": [
        "BLACK_BURST",
        "TRI_SYNC",
        "10MHZ",
        "WCLK",
        "AES3ID"
      ]
    },
    {
      "name": "INPUT B",
      "direction": "IN",
      "connectorId": "BNC_f",
      "compatibleSignalTypes": [
        "BLACK_BURST",
        "TRI_SYNC",
        "10MHZ",
        "WCLK",
        "AES3ID"
      ]
    },
    {
      "name": "UNIVERSAL OUTPUT 1",
      "direction": "OUT",
      "connectorId": "BNC_f",
      "compatibleSignalTypes": [
        "BLACK_BURST",
        "TRI_SYNC",
        "10MHZ",
        "WCLK",
        "AES3ID",
        "LTC_UNBAL"
      ]
    },
    {
      "name": "UNIVERSAL OUTPUT 2",
      "direction": "OUT",
      "connectorId": "BNC_f",
      "compatibleSignalTypes": [
        "BLACK_BURST",
        "TRI_SYNC",
        "10MHZ",
        "WCLK",
        "AES3ID",
        "LTC_UNBAL"
      ]
    },
    {
      "name": "UNIVERSAL OUTPUT 3",
      "direction": "OUT",
      "connectorId": "BNC_f",
      "compatibleSignalTypes": [
        "BLACK_BURST",
        "TRI_SYNC",
        "10MHZ",
        "WCLK",
        "AES3ID",
        "LTC_UNBAL"
      ]
    },
    {
      "name": "UNIVERSAL OUTPUT 4",
      "direction": "OUT",
      "connectorId": "BNC_f",
      "compatibleSignalTypes": [
        "BLACK_BURST",
        "TRI_SYNC",
        "10MHZ",
        "WCLK",
        "AES3ID",
        "LTC_UNBAL"
      ]
    },
    {
      "name": "UNIVERSAL OUTPUT 5",
      "direction": "OUT",
      "connectorId": "BNC_f",
      "compatibleSignalTypes": [
        "BLACK_BURST",
        "TRI_SYNC",
        "10MHZ",
        "WCLK",
        "AES3ID",
        "LTC_UNBAL"
      ]
    },
    {
      "name": "UNIVERSAL OUTPUT 6",
      "direction": "OUT",
      "connectorId": "BNC_f",
      "compatibleSignalTypes": [
        "BLACK_BURST",
        "TRI_SYNC",
        "10MHZ",
        "WCLK",
        "AES3ID",
        "LTC_UNBAL"
      ]
    },
    {
      "name": "UNIVERSAL OUTPUT 7",
      "direction": "OUT",
      "connectorId": "BNC_f",
      "compatibleSignalTypes": [
        "BLACK_BURST",
        "TRI_SYNC",
        "10MHZ",
        "WCLK",
        "AES3ID",
        "LTC_UNBAL"
      ]
    },
    {
      "name": "UNIVERSAL OUTPUT 8",
      "direction": "OUT",
      "connectorId": "BNC_f",
      "compatibleSignalTypes": [
        "BLACK_BURST",
        "TRI_SYNC",
        "10MHZ",
        "WCLK",
        "AES3ID",
        "LTC_UNBAL"
      ]
    },
    {
      "name": "UNIVERSAL OUTPUT 9",
      "direction": "OUT",
      "connectorId": "BNC_f",
      "compatibleSignalTypes": [
        "BLACK_BURST",
        "TRI_SYNC",
        "10MHZ",
        "WCLK",
        "AES3ID",
        "LTC_UNBAL"
      ]
    },
    {
      "name": "UNIVERSAL OUTPUT 10",
      "direction": "OUT",
      "connectorId": "BNC_f",
      "compatibleSignalTypes": [
        "BLACK_BURST",
        "TRI_SYNC",
        "10MHZ",
        "WCLK",
        "AES3ID",
        "LTC_UNBAL"
      ]
    },
    {
      "name": "UNIVERSAL OUTPUT 11",
      "direction": "OUT",
      "connectorId": "BNC_f",
      "compatibleSignalTypes": [
        "BLACK_BURST",
        "TRI_SYNC",
        "10MHZ",
        "WCLK",
        "AES3ID",
        "LTC_UNBAL"
      ]
    },
    {
      "name": "UNIVERSAL OUTPUT 12",
      "direction": "OUT",
      "connectorId": "BNC_f",
      "compatibleSignalTypes": [
        "BLACK_BURST",
        "TRI_SYNC",
        "10MHZ",
        "WCLK",
        "AES3ID",
        "LTC_UNBAL"
      ]
    },
    {
      "name": "UNIVERSAL OUTPUT 13",
      "direction": "OUT",
      "connectorId": "BNC_f",
      "compatibleSignalTypes": [
        "BLACK_BURST",
        "TRI_SYNC",
        "10MHZ",
        "WCLK",
        "AES3ID",
        "LTC_UNBAL"
      ]
    },
    {
      "name": "UNIVERSAL OUTPUT 14",
      "direction": "OUT",
      "connectorId": "BNC_f",
      "compatibleSignalTypes": [
        "BLACK_BURST",
        "TRI_SYNC",
        "10MHZ",
        "WCLK",
        "AES3ID",
        "LTC_UNBAL"
      ]
    },
    {
      "name": "UNIVERSAL OUTPUT 15",
      "direction": "OUT",
      "connectorId": "BNC_f",
      "compatibleSignalTypes": [
        "BLACK_BURST",
        "TRI_SYNC",
        "10MHZ",
        "WCLK",
        "AES3ID",
        "LTC_UNBAL"
      ]
    },
    {
      "name": "UNIVERSAL OUTPUT 16",
      "direction": "OUT",
      "connectorId": "BNC_f",
      "compatibleSignalTypes": [
        "BLACK_BURST",
        "TRI_SYNC",
        "10MHZ",
        "WCLK",
        "AES3ID",
        "LTC_UNBAL"
      ]
    }
  ],
  "moduleSlotTypes": []
}

=== jan-ldwg/site_manager_templates/devicetypes/telestream/telestream-mpp-300.json
{
  "version": "1.0",
  "id": "telestream-mpp-300",
  "name": "PRISM MPP-300",
  "manufacturerId": "telestream",
  "orderCode": null,
  "orderNumber": null,
  "climateLoad": 160,
  "rackType": "19INCH",
  "rackHeight": 1,
  "rackDepth": 285,
  "portTypes": [
    {
      "name": "LAN",
      "direction": "UP",
      "connectorId": "RJ45_f",
      "compatibleSignalTypes": ["1000BASE_T"]
    },
    {
      "name": "REF IN",
      "direction": "IN",
      "connectorId": "HD_BNC_f",
      "compatibleSignalTypes": ["BLACK_BURST", "TRI_SYNC"]
    },
    {
      "name": "REF OUT",
      "direction": "OUT",
      "connectorId": "HD_BNC_f",
      "compatibleSignalTypes": ["BLACK_BURST", "TRI_SYNC", "PPS"]
    },
    {
      "name": "SDI IN 1 EYE",
      "direction": "IN",
      "connectorId": "HD_BNC_f",
      "compatibleSignalTypes": [
        "SDI_SD_CU",
        "SDI_HD_CU",
        "SDI_3G_CU",
        "SDI_12G_CU"
      ]
    },
    {
      "name": "SDI OUT 1",
      "direction": "OUT",
      "connectorId": "HD_BNC_f",
      "compatibleSignalTypes": [
        "SDI_SD_CU",
        "SDI_HD_CU",
        "SDI_3G_CU",
        "SDI_12G_CU"
      ]
    },
    {
      "name": "SDI IN 2",
      "direction": "IN",
      "connectorId": "HD_BNC_f",
      "compatibleSignalTypes": [
        "SDI_SD_CU",
        "SDI_HD_CU",
        "SDI_3G_CU",
        "SDI_12G_CU"
      ]
    },
    {
      "name": "SDI OUT 2",
      "direction": "OUT",
      "connectorId": "HD_BNC_f",
      "compatibleSignalTypes": [
        "SDI_SD_CU",
        "SDI_HD_CU",
        "SDI_3G_CU",
        "SDI_12G_CU"
      ]
    },
    {
      "name": "SDI IN 3",
      "direction": "IN",
      "connectorId": "HD_BNC_f",
      "compatibleSignalTypes": [
        "SDI_SD_CU",
        "SDI_HD_CU",
        "SDI_3G_CU",
        "SDI_12G_CU"
      ]
    },
    {
      "name": "SDI OUT 3",
      "direction": "OUT",
      "connectorId": "HD_BNC_f",
      "compatibleSignalTypes": [
        "SDI_SD_CU",
        "SDI_HD_CU",
        "SDI_3G_CU",
        "SDI_12G_CU"
      ]
    },
    {
      "name": "SDI IN 4",
      "direction": "IN",
      "connectorId": "HD_BNC_f",
      "compatibleSignalTypes": [
        "SDI_SD_CU",
        "SDI_HD_CU",
        "SDI_3G_CU",
        "SDI_12G_CU"
      ]
    },
    {
      "name": "SDI OUT 4",
      "direction": "OUT",
      "connectorId": "HD_BNC_f",
      "compatibleSignalTypes": [
        "SDI_SD_CU",
        "SDI_HD_CU",
        "SDI_3G_CU",
        "SDI_12G_CU"
      ]
    },
    {
      "name": "AUX OUT",
      "direction": "OUT",
      "connectorId": "HD_BNC_f",
      "compatibleSignalTypes": [
        "SDI_SD_CU",
        "SDI_HD_CU",
        "SDI_3G_CU",
        "SDI_12G_CU"
      ]
    },
    {
      "name": "DP1",
      "direction": "OUT",
      "connectorId": "DISPLAYPORT_f",
      "compatibleSignalTypes": ["DP"]
    },
    {
      "name": "DP2",
      "direction": "OUT",
      "connectorId": "DISPLAYPORT_f",
      "compatibleSignalTypes": ["DP"]
    },
    {
      "name": "USB (Rear)",
      "direction": "OUT",
      "connectorId": "USB3.0A_f",
      "compatibleSignalTypes": ["USB_1", "USB_11", "USB_2", "USB_32_GEN1X1"]
    },
    {
      "name": "USB (Rear)",
      "direction": "OUT",
      "connectorId": "USB3.0A_f",
      "compatibleSignalTypes": ["USB_1", "USB_11", "USB_2", "USB_32_GEN1X1"]
    },
    {
      "name": "ANALOG AUDIO OUT 1-8",
      "direction": "OUT",
      "connectorId": "DSUB25p_f",
      "compatibleSignalTypes": ["AES59_ANA"]
    },
    {
      "name": "GPIO",
      "direction": "IN",
      "connectorId": "DSUB15p_MICRO_f",
      "compatibleSignalTypes": ["GPIO"]
    },
    {
      "name": "Line Out",
      "direction": "OUT",
      "connectorId": "TRS_35_f",
      "compatibleSignalTypes": ["AUDIO_UNBAL_ANA_STEREO"]
    },
    {
      "name": "USB (Front)",
      "direction": "OUT",
      "connectorId": "USB3.0A_f",
      "compatibleSignalTypes": ["USB_1", "USB_11", "USB_2", "USB_32_GEN1X1"]
    },
    {
      "name": "USB (Front)",
      "direction": "OUT",
      "connectorId": "USB3.0A_f",
      "compatibleSignalTypes": ["USB_1", "USB_11", "USB_2", "USB_32_GEN1X1"]
    },
    {
      "name": "Headphones",
      "direction": "OUT",
      "connectorId": "TRS_35_f",
      "compatibleSignalTypes": ["PHONES_ANA"]
    }
  ],
  "moduleSlotTypes": [
    {
      "name": "10/25GE 1",
      "compatibleModuleSlotFormFactors": ["sfp28", "sfpplus"],
      "compatibleModuleTypes": [
        "telestream-mp-sfp-10gelr",
        "telestream-mp-sfp-10gesr",
        "telestream-mp-sfp-25gelr",
        "telestream-mp-sfp-25gesr"
      ],
      "incompatibleModuleTypes": []
    },
    {
      "name": "10/25GE 2",
      "compatibleModuleSlotFormFactors": ["sfp28", "sfpplus"],
      "compatibleModuleTypes": [
        "telestream-mp-sfp-10gelr",
        "telestream-mp-sfp-10gesr",
        "telestream-mp-sfp-25gelr",
        "telestream-mp-sfp-25gesr"
      ],
      "incompatibleModuleTypes": []
    }
  ]
}

=== jan-ldwg/site_manager_templates/devicetypes/bricasti/bricasti-m7.json
{
  "version": "1.0",
  "id": "bricasti-m7",
  "name": "M7",
  "manufacturerId": "bricasti",
  "orderCode": null,
  "orderNumber": null,
  "climateLoad": 60,
  "rackType": "19INCH",
  "rackHeight": 1,
  "rackDepth": 297,
  "portTypes": [
    {
      "name": "Midi In",
      "direction": "IN",
      "connectorId": "DIN5p_f",
      "compatibleSignalTypes": ["MIDI"]
    },
    {
      "name": "Midi Out",
      "direction": "OUT",
      "connectorId": "DIN5p_f",
      "compatibleSignalTypes": ["MIDI"]
    },
    {
      "name": "Remote",
      "direction": "IN",
      "connectorId": "DSUB9p_f",
      "compatibleSignalTypes": ["RS_422"]
    },
    {
      "name": "Loop thru",
      "direction": "OUT",
      "connectorId": "DSUB9p_m",
      "compatibleSignalTypes": ["RS_422"]
    },
    {
      "name": "AES In",
      "direction": "IN",
      "connectorId": "XLR3p_f",
      "compatibleSignalTypes": ["AES3"]
    },
    {
      "name": "AES Out",
      "direction": "OUT",
      "connectorId": "XLR3p_m",
      "compatibleSignalTypes": ["AES3"]
    },
    {
      "name": "Analog Left In",
      "direction": "IN",
      "connectorId": "XLR3p_f",
      "compatibleSignalTypes": ["AUDIO_BAL_ANA"]
    },
    {
      "name": "Analog Right In",
      "direction": "IN",
      "connectorId": "XLR3p_f",
      "compatibleSignalTypes": ["AUDIO_BAL_ANA"]
    },

    {
      "name": "Analog Left Out",
      "direction": "OUT",
      "connectorId": "XLR3p_m",
      "compatibleSignalTypes": ["AUDIO_BAL_ANA"]
    },
    {
      "name": "Analog Right Out",
      "direction": "OUT",
      "connectorId": "XLR3p_m",
      "compatibleSignalTypes": ["AUDIO_BAL_ANA"]
    }
  ]
}

=== jan-ldwg/site_manager_templates/devicetypes/telestream/telestream-mpp-100.json
{
  "version": "1.0",
  "id": "telestream-mpp-100",
  "name": "PRISM MPP-100",
  "manufacturerId": "telestream",
  "orderCode": null,
  "orderNumber": null,
  "climateLoad": 160,
  "rackType": "19INCH",
  "rackHeight": 1,
  "rackDepth": 285,
  "portTypes": [
    {
      "name": "LAN",
      "direction": "UP",
      "connectorId": "RJ45_f",
      "compatibleSignalTypes": ["1000BASE_T"]
    },
    {
      "name": "REF IN",
      "direction": "IN",
      "connectorId": "HD_BNC_f",
      "compatibleSignalTypes": ["BLACK_BURST", "TRI_SYNC"]
    },
    {
      "name": "REF OUT",
      "direction": "OUT",
      "connectorId": "HD_BNC_f",
      "compatibleSignalTypes": ["BLACK_BURST", "TRI_SYNC", "PPS"]
    },
    {
      "name": "SDI IN 1",
      "direction": "IN",
      "connectorId": "HD_BNC_f",
      "compatibleSignalTypes": [
        "SDI_SD_CU",
        "SDI_HD_CU",
        "SDI_3G_CU",
        "SDI_12G_CU"
      ]
    },
    {
      "name": "SDI OUT 1",
      "direction": "OUT",
      "connectorId": "HD_BNC_f",
      "compatibleSignalTypes": [
        "SDI_SD_CU",
        "SDI_HD_CU",
        "SDI_3G_CU",
        "SDI_12G_CU"
      ]
    },
    {
      "name": "SDI IN 2",
      "direction": "IN",
      "connectorId": "HD_BNC_f",
      "compatibleSignalTypes": [
        "SDI_SD_CU",
        "SDI_HD_CU",
        "SDI_3G_CU",
        "SDI_12G_CU"
      ]
    },
    {
      "name": "SDI OUT 2",
      "direction": "OUT",
      "connectorId": "HD_BNC_f",
      "compatibleSignalTypes": [
        "SDI_SD_CU",
        "SDI_HD_CU",
        "SDI_3G_CU",
        "SDI_12G_CU"
      ]
    },
    {
      "name": "SDI IN 3",
      "direction": "IN",
      "connectorId": "HD_BNC_f",
      "compatibleSignalTypes": [
        "SDI_SD_CU",
        "SDI_HD_CU",
        "SDI_3G_CU",
        "SDI_12G_CU"
      ]
    },
    {
      "name": "SDI OUT 3",
      "direction": "OUT",
      "connectorId": "HD_BNC_f",
      "compatibleSignalTypes": [
        "SDI_SD_CU",
        "SDI_HD_CU",
        "SDI_3G_CU",
        "SDI_12G_CU"
      ]
    },
    {
      "name": "SDI IN 4",
      "direction": "IN",
      "connectorId": "HD_BNC_f",
      "compatibleSignalTypes": [
        "SDI_SD_CU",
        "SDI_HD_CU",
        "SDI_3G_CU",
        "SDI_12G_CU"
      ]
    },
    {
      "name": "SDI OUT 4",
      "direction": "OUT",
      "connectorId": "HD_BNC_f",
      "compatibleSignalTypes": [
        "SDI_SD_CU",
        "SDI_HD_CU",
        "SDI_3G_CU",
        "SDI_12G_CU"
      ]
    },
    {
      "name": "AUX OUT",
      "direction": "OUT",
      "connectorId": "HD_BNC_f",
      "compatibleSignalTypes": [
        "SDI_SD_CU",
        "SDI_HD_CU",
        "SDI_3G_CU",
        "SDI_12G_CU"
      ]
    },
    {
      "name": "DP1",
      "direction": "OUT",
      "connectorId": "DISPLAYPORT_f",
      "compatibleSignalTypes": ["DP"]
    },
    {
      "name": "DP2",
      "direction": "OUT",
      "connectorId": "DISPLAYPORT_f",
      "compatibleSignalTypes": ["DP"]
    },
    {
      "name": "USB (Rear)",
      "direction": "OUT",
      "connectorId": "USB3.0A_f",
      "compatibleSignalTypes": ["USB_1", "USB_11", "USB_2", "USB_32_GEN1X1"]
    },
    {
      "name": "USB (Rear)",
      "direction": "OUT",
      "connectorId": "USB3.0A_f",
      "compatibleSignalTypes": ["USB_1", "USB_11", "USB_2", "USB_32_GEN1X1"]
    },
    {
      "name": "GPIO",
      "direction": "IN",
      "connectorId": "DSUB15p_MICRO_f",
      "compatibleSignalTypes": ["GPIO"]
    },
    {
      "name": "USB (Front)",
      "direction": "OUT",
      "connectorId": "USB3.0A_f",
      "compatibleSignalTypes": ["USB_1", "USB_11", "USB_2", "USB_32_GEN1X1"]
    },
    {
      "name": "USB (Front)",
      "direction": "OUT",
      "connectorId": "USB3.0A_f",
      "compatibleSignalTypes": ["USB_1", "USB_11", "USB_2", "USB_32_GEN1X1"]
    },
    {
      "name": "Headphones",
      "direction": "OUT",
      "connectorId": "TRS_35_f",
      "compatibleSignalTypes": ["PHONES_ANA"]
    }
  ]
}

=== jan-ldwg/site_manager_templates/devicetypes/postium/postium-obm-n240.json
{
  "version": "1.0",
  "id": "postium-obm-n240",
  "name": "OBM-N240",
  "manufacturerId": "postium",
  "orderCode": null,
  "orderNumber": null,
  "climateLoad": 40,
  "rackType": "NONE",
  "portTypes": [
    {
      "name": "LAN",
      "direction": "UP",
      "connectorId": "RJ45_f",
      "compatibleSignalTypes": ["10BASE_T", "100BASE_TX"]
    },
    {
      "name": "REMOTE",
      "direction": "IN",
      "connectorId": "RJ45_f",
      "compatibleSignalTypes": ["GPIO"]
    },
    {
      "name": "RS422 IN",
      "direction": "IN",
      "connectorId": "RJ45_f",
      "compatibleSignalTypes": ["RS_422"]
    },
    {
      "name": "RS422 OUT",
      "direction": "OUT",
      "connectorId": "RJ45_f",
      "compatibleSignalTypes": ["RS_422"]
    },
    {
      "name": "HDMI-IN",
      "direction": "IN",
      "connectorId": "HDMI_A_f",
      "compatibleSignalTypes": ["HDMI", "DVI_I", "DVI_D"]
    },
    {
      "name": "DVI",
      "direction": "IN",
      "connectorId": "DVI_I_DL_f",
      "compatibleSignalTypes": ["HDMI", "DVI_D"]
    },
    {
      "name": "SDI-1 IN",
      "direction": "IN",
      "connectorId": "BNC_f",
      "compatibleSignalTypes": ["SDI_SD_CU", "SDI_HD_CU", "SDI_3G_CU"]
    },
    {
      "name": "SDI-1 OUT",
      "direction": "OUT",
      "connectorId": "BNC_f",
      "compatibleSignalTypes": ["SDI_SD_CU", "SDI_HD_CU", "SDI_3G_CU"]
    },
    {
      "name": "SDI-2 IN",
      "direction": "IN",
      "connectorId": "BNC_f",
      "compatibleSignalTypes": ["SDI_SD_CU", "SDI_HD_CU", "SDI_3G_CU"]
    },
    {
      "name": "SDI-2 OUT",
      "direction": "OUT",
      "connectorId": "BNC_f",
      "compatibleSignalTypes": ["SDI_SD_CU", "SDI_HD_CU", "SDI_3G_CU"]
    },
    {
      "name": "Y(CVBS1)",
      "direction": "IN",
      "connectorId": "BNC_f",
      "compatibleSignalTypes": ["CVBS", "Y"]
    },
    {
      "name": "Pb",
      "direction": "IN",
      "connectorId": "BNC_f",
      "compatibleSignalTypes": ["PB"]
    },
    {
      "name": "Pr",
      "direction": "IN",
      "connectorId": "BNC_f",
      "compatibleSignalTypes": ["PR"]
    },
    {
      "name": "AUDIO IN",
      "direction": "IN",
      "connectorId": "TRS_35_f",
      "compatibleSignalTypes": ["AUDIO_UNBAL_ANA_STEREO"]
    },
    {
      "name": "Headphones",
      "direction": "OUT",
      "connectorId": "TRS_35_f",
      "compatibleSignalTypes": ["PHONES_ANA"]
    },
    {
      "name": "USB",
      "direction": "OUT",
      "connectorId": "USB2.0A_f",
      "compatibleSignalTypes": ["USB_1", "USB_11", "USB_2"]
    }
  ]
}
