=== jan-ldwg/site_manager_templates/schemas/devicetype.schema.json
{
  "$schema": "https://json-schema.org/draft/2020-12/schema",
  "title": "devicetype",
  "description": "JSON document describing a new device type",
  "type": "object",
  "properties": {
    "version": {
      "description": "Version number of the template. Minor version must be increased with every change. Major version must only be changed when targeting a different API version.",
      "type": "string",
      "pattern": "^\\d{1,2}\\.\\d{1,2}$"
    },
    "id": {
      "description": "Id of the device type. Consists of id of manufacturer followed by id of device type. See documentation for rules.",
      "type": "string",
      "pattern": "^(?=.{1,48}$)(?!.*--)[a-z](?:[a-z-]{0,14}[a-z])?-[a-z0-9](?:[a-z0-9-]*[a-z0-9])?$",
      "maxLength": 48
    },
    "name": {
      "description": "Name of the device as given by manufacturer",
      "type": "string",
      "maxLength": 256
    },
    "manufacturerId": {
      "description": "Id of the manufacturer of the device type.",
      "type": "string",
      "pattern": "^(?!.*--)[a-z](?:[a-z-]{0,14}[a-z])$",
      "maxLength": 16
    },
    "orderCode": {
      "description": "Order code for the device type as used by the manufacturer.",
      "type": ["string", "null"]
    },
    "orderNumber": {
      "description": "Order number for the device type as used by the manufacturer.",
      "type": ["string", "null"]
    },
    "climateLoad": {
      "description": "The maximum heat dissipation of the device type.",
      "type": ["integer", "null"],
      "minimum": 0
    },
    "rackType": {
      "description": "The type of rack the device can be mounted in.",
      "enum": ["19INCH", "NONE"]
    },
    "rackHeight": {
      "description": "The height the device occupies inside a rack in units of that rack type.",
      "type": "integer"
    },
    "rackDepth": {
      "description": "The distance between the mounting plane of the rack and the rear most potrusion of the device in mm.",
      "type": "integer",
      "minimum": 0
    },
    "portTypes": {
      "description": "List of all types of ports on the device type.",
      "type": "array",
      "items": {
        "type": "object",
        "properties": {
          "name": {
            "description": "Name of the port, as printed on the device.",
            "type": "string"
          },
          "direction": {
            "description": "Direction of the port type. See documentation for explainations of the possible values.",
            "enum": [
              "IN",
              "OUT",
              "INOUT",
              "BIDI",
              "UP",
              "DOWN",
              "FRONT",
              "REAR"
            ]
          },
          "connectorId": {
            "description": "Id of the connector.",
            "type": "string",
            "pattern": "^[A-Za-z0-9](?:[A-Za-z0-9]|[_.](?=[A-Za-z0-9]))*_(?:f|m|h)$"
          },
          "compatibleSignalTypes": {
            "description": "List of signal types that are compatible with this port.",
            "type": "array",
            "items": {
              "type": "string",
              "pattern": "^(?!.*--)(?:[a-z](?:[a-z-]{0,14}[a-z])?_)?[A-Z0-9]+(?:_[A-Z0-9]+)*$"
            },
            "uniqueItems": true
          }
        },
        "required": [
          "name",
          "direction",
          "connectorId",
          "compatibleSignalTypes"
        ],
        "additionalProperties": false
      }
    },
    "moduleSlotTypes": {
      "description": "List of all types of module slots on the device type.",
      "type": "array",
      "items": {
        "type": "object",
        "properties": {
          "name": {
            "description": "Name of the module slot, as labeled on the device.",
            "type": "string"
          },
          "canSpan": {
            "description": "Indicates wether a module can span into the next slot",
            "type": "boolean"
          },
          "compatibleModuleSlotFormFactors": {
            "description": "List of module slot factors that can physically fit into the slot.",
            "type": "array",
            "uniqueItems": true,
            "items": {
              "type": "string",
              "pattern": "^[a-z0-9]+(?:-[a-z0-9]+)*$"
            }
          },
          "compatibleModuleTypes": {
            "description": "List of module types that are guranteed by the manufacturer to work in this slot.",
            "type": "array",
            "uniqueItems": true,
            "items": {
              "type": "string",
              "pattern": "^(?=.{1,48}$)(?!.*--)[a-z](?:[a-z-]{0,14}[a-z])?-[a-z0-9](?:[a-z0-9-]*[a-z0-9])?$"
            }
          },
          "incompatibleModuleTypes": {
            "description": "List of module types that are guranteed by the manufacturer not work in this module slot.",
            "type": "array",
            "uniqueItems": true,
            "items": {
              "type": "string",
              "pattern": "^(?=.{1,48}$)(?!.*--)[a-z](?:[a-z-]{0,14}[a-z])?-[a-z0-9](?:[a-z0-9-]*[a-z0-9])?$"
            }
          }
        },
        "required": [
          "name",
          "compatibleModuleSlotFormFactors",
          "compatibleModuleTypes",
          "incompatibleModuleTypes"
        ],
        "additionalProperties": false
      }
    }
  },
  "required": ["version", "id", "name", "manufacturerId", "rackType"],
  "additionalProperties": false
}

=== jan-ldwg/site_manager_templates/devicetypes/netgear/netgear-pr460x.json
{
  "version": "1.0",
  "id": "netgear-pr460x",
  "name": "PR460X",
  "manufacturerId": "netgear",
  "orderCode": null,
  "orderNumber": "pr460x",
  "climateLoad": 130,
  "rackType": "19INCH",
  "rackHeight": 1,
  "rackDepth": 100,
  "portTypes": [
    {
      "name": "LAN1",
      "direction": "DOWN",
      "connectorId": "RJ45_f",
      "compatibleSignalTypes": ["1000BASE_T", "2_5GBASE_T"]
    },
    {
      "name": "LAN2",
      "direction": "DOWN",
      "connectorId": "RJ45_f",
      "compatibleSignalTypes": ["1000BASE_T", "2_5GBASE_T"]
    },
    {
      "name": "LAN3",
      "direction": "DOWN",
      "connectorId": "RJ45_f",
      "compatibleSignalTypes": ["1000BASE_T", "2_5GBASE_T"]
    },
    {
      "name": "WAN1",
      "direction": "DOWN",
      "connectorId": "RJ45_f",
      "compatibleSignalTypes": ["1000BASE_T", "2_5GBASE_T"]
    },
    {
      "name": "LAN5 WAN2",
      "direction": "DOWN",
      "connectorId": "RJ45_f",
      "compatibleSignalTypes": [
        "1000BASE_T",
        "2_5GBASE_T",
        "5GBASE_T",
        "10GBASE_T"
      ]
    }
  ],
  "moduleSlotTypes": [
    {
      "name": "LAN4",
      "compatibleModuleSlotFormFactors": ["sfp", "sfpplus"],
      "compatibleModuleTypes": [
        "netgear-agm731f",
        "netgear-agm732f",
        "netgear-agm734",
        "netgear-axm761",
        "netgear-axm762",
        "netgear-axm763",
        "netgear-axm764",
        "netgear-axm765"
      ],
      "incompatibleModuleTypes": []
    }
  ]
}

=== jan-ldwg/site_manager_templates/devicetypes/cisco/cisco-nexus-9348gc-fx3.json
{
  "version": "1.1",
  "id": "cisco-nexus-9348gc-fx3",
  "name": "Nexus 9348GC-FX3",
  "manufacturerId": "cisco",
  "orderCode": null,
  "orderNumber": "N9K-C9348GC-FX3",
  "climateLoad": 242,
  "rackType": "19INCH",
  "rackHeight": 1,
  "rackDepth": 533,
  "portTypes": [
    {
      "name": "Console",
      "direction": "IN",
      "connectorId": "RJ45_f",
      "compatibleSignalTypes": ["RS_232"]
    },
    {
      "name": "USB",
      "direction": "OUT",
      "connectorId": "USB2.0A_f",
      "compatibleSignalTypes": ["USB_1", "USB_11", "USB_2"]
    },
    {
      "name": "Management",
      "direction": "UP",
      "connectorId": "RJ45_f",
      "compatibleSignalTypes": ["10BASE_T", "100BASE_TX", "1000BASE_T"]
    },
    {
      "name": "1",
      "direction": "DOWN",
      "connectorId": "RJ45_f",
      "compatibleSignalTypes": ["100BASE_TX", "1000BASE_T"]
    },
    {
      "name": "2",
      "direction": "DOWN",
      "connectorId": "RJ45_f",
      "compatibleSignalTypes": ["100BASE_TX", "1000BASE_T"]
    },
    {
      "name": "3",
      "direction": "DOWN",
      "connectorId": "RJ45_f",
      "compatibleSignalTypes": ["100BASE_TX", "1000BASE_T"]
    },
    {
      "name": "4",
      "direction": "DOWN",
      "connectorId": "RJ45_f",
      "compatibleSignalTypes": ["100BASE_TX", "1000BASE_T"]
    },
    {
      "name": "5",
      "direction": "DOWN",
      "connectorId": "RJ45_f",
      "compatibleSignalTypes": ["100BASE_TX", "1000BASE_T"]
    },
    {
      "name": "6",
      "direction": "DOWN",
      "connectorId": "RJ45_f",
      "compatibleSignalTypes": ["100BASE_TX", "1000BASE_T"]
    },
    {
      "name": "7",
      "direction": "DOWN",
      "connectorId": "RJ45_f",
      "compatibleSignalTypes": ["100BASE_TX", "1000BASE_T"]
    },
    {
      "name": "8",
      "direction": "DOWN",
      "connectorId": "RJ45_f",
      "compatibleSignalTypes": ["100BASE_TX", "1000BASE_T"]
    },
    {
      "name": "9",
      "direction": "DOWN",
      "connectorId": "RJ45_f",
      "compatibleSignalTypes": ["100BASE_TX", "1000BASE_T"]
    },
    {
      "name": "10",
      "direction": "DOWN",
      "connectorId": "RJ45_f",
      "compatibleSignalTypes": ["100BASE_TX", "1000BASE_T"]
    },
    {
      "name": "11",
      "direction": "DOWN",
      "connectorId": "RJ45_f",
      "compatibleSignalTypes": ["100BASE_TX", "1000BASE_T"]
    },

    {
      "name": "12",
      "direction": "DOWN",
      "connectorId": "RJ45_f",
      "compatibleSignalTypes": ["100BASE_TX", "1000BASE_T"]
    },
    {
      "name": "13",
      "direction": "DOWN",
      "connectorId": "RJ45_f",
      "compatibleSignalTypes": ["100BASE_TX", "1000BASE_T"]
    },
    {
      "name": "14",
      "direction": "DOWN",
      "connectorId": "RJ45_f",
      "compatibleSignalTypes": ["100BASE_TX", "1000BASE_T"]
    },
    {
      "name": "15",
      "direction": "DOWN",
      "connectorId": "RJ45_f",
      "compatibleSignalTypes": ["100BASE_TX", "1000BASE_T"]
    },
    {
      "name": "16",
      "direction": "DOWN",
      "connectorId": "RJ45_f",
      "compatibleSignalTypes": ["100BASE_TX", "1000BASE_T"]
    },
    {
      "name": "17",
      "direction": "DOWN",
      "connectorId": "RJ45_f",
      "compatibleSignalTypes": ["100BASE_TX", "1000BASE_T"]
    },
    {
      "name": "18",
      "direction": "DOWN",
      "connectorId": "RJ45_f",
      "compatibleSignalTypes": ["100BASE_TX", "1000BASE_T"]
    },
    {
      "name": "19",
      "direction": "DOWN",
      "connectorId": "RJ45_f",
      "compatibleSignalTypes": ["100BASE_TX", "1000BASE_T"]
    },
    {
      "name": "20",
      "direction": "DOWN",
      "connectorId": "RJ45_f",
      "compatibleSignalTypes": ["100BASE_TX", "1000BASE_T"]
    },
    {
      "name": "21",
      "direction": "DOWN",
      "connectorId": "RJ45_f",
      "compatibleSignalTypes": ["100BASE_TX", "1000BASE_T"]
    },
    {
      "name": "22",
      "direction": "DOWN",
      "connectorId": "RJ45_f",
      "compatibleSignalTypes": ["100BASE_TX", "1000BASE_T"]
    },
    {
      "name": "23",
      "direction": "DOWN",
      "connectorId": "RJ45_f",
      "compatibleSignalTypes": ["100BASE_TX", "1000BASE_T"]
    },
    {
      "name": "24",
      "direction": "DOWN",
      "connectorId": "RJ45_f",
      "compatibleSignalTypes": ["100BASE_TX", "1000BASE_T"]
    },
    {
      "name": "25",
      "direction": "DOWN",
      "connectorId": "RJ45_f",
      "compatibleSignalTypes": ["100BASE_TX", "1000BASE_T"]
    },
    {
      "name": "26",
      "direction": "DOWN",
      "connectorId": "RJ45_f",
      "compatibleSignalTypes": ["100BASE_TX", "1000BASE_T"]
    },
    {
      "name": "27",
      "direction": "DOWN",
      "connectorId": "RJ45_f",
      "compatibleSignalTypes": ["100BASE_TX", "1000BASE_T"]
    },

    {
      "name": "28",
      "direction": "DOWN",
      "connectorId": "RJ45_f",
      "compatibleSignalTypes": ["100BASE_TX", "1000BASE_T"]
    },
    {
      "name": "29",
      "direction": "DOWN",
      "connectorId": "RJ45_f",
      "compatibleSignalTypes": ["100BASE_TX", "1000BASE_T"]
    },
    {
      "name": "30",
      "direction": "DOWN",
      "connectorId": "RJ45_f",
      "compatibleSignalTypes": ["100BASE_TX", "1000BASE_T"]
    },
    {
      "name": "31",
      "direction": "DOWN",
      "connectorId": "RJ45_f",
      "compatibleSignalTypes": ["100BASE_TX", "1000BASE_T"]
    },
    {
      "name": "32",
      "direction": "DOWN",
      "connectorId": "RJ45_f",
      "compatibleSignalTypes": ["100BASE_TX", "1000BASE_T"]
    },
    {
      "name": "33",
      "direction": "DOWN",
      "connectorId": "RJ45_f",
      "compatibleSignalTypes": ["100BASE_TX", "1000BASE_T"]
    },
    {
      "name": "34",
      "direction": "DOWN",
      "connectorId": "RJ45_f",
      "compatibleSignalTypes": ["100BASE_TX", "1000BASE_T"]
    },
    {
      "name": "35",
      "direction": "DOWN",
      "connectorId": "RJ45_f",
      "compatibleSignalTypes": ["100BASE_TX", "1000BASE_T"]
    },
    {
      "name": "36",
      "direction": "DOWN",
      "connectorId": "RJ45_f",
      "compatibleSignalTypes": ["100BASE_TX", "1000BASE_T"]
    },
    {
      "name": "37",
      "direction": "DOWN",
      "connectorId": "RJ45_f",
      "compatibleSignalTypes": ["100BASE_TX", "1000BASE_T"]
    },
    {
      "name": "38",
      "direction": "DOWN",
      "connectorId": "RJ45_f",
      "compatibleSignalTypes": ["100BASE_TX", "1000BASE_T"]
    },
    {
      "name": "39",
      "direction": "DOWN",
      "connectorId": "RJ45_f",
      "compatibleSignalTypes": ["100BASE_TX", "1000BASE_T"]
    },
    {
      "name": "40",
      "direction": "DOWN",
      "connectorId": "RJ45_f",
      "compatibleSignalTypes": ["100BASE_TX", "1000BASE_T"]
    },
    {
      "name": "41",
      "direction": "DOWN",
      "connectorId": "RJ45_f",
      "compatibleSignalTypes": ["100BASE_TX", "1000BASE_T"]
    },
    {
      "name": "42",
      "direction": "DOWN",
      "connectorId": "RJ45_f",
      "compatibleSignalTypes": ["100BASE_TX", "1000BASE_T"]
    },
    {
      "name": "43",
      "direction": "DOWN",
      "connectorId": "RJ45_f",
      "compatibleSignalTypes": ["100BASE_TX", "1000BASE_T"]
    },
    {
      "name": "44",
      "direction": "DOWN",
      "connectorId": "RJ45_f",
      "compatibleSignalTypes": ["100BASE_TX", "1000BASE_T"]
    },
    {
      "name": "45",
      "direction": "DOWN",
      "connectorId": "RJ45_f",
      "compatibleSignalTypes": ["100BASE_TX", "1000BASE_T"]
    },
    {
      "name": "46",
      "direction": "DOWN",
      "connectorId": "RJ45_f",
      "compatibleSignalTypes": ["100BASE_TX", "1000BASE_T"]
    },
    {
      "name": "47",
      "direction": "DOWN",
      "connectorId": "RJ45_f",
      "compatibleSignalTypes": ["100BASE_TX", "1000BASE_T"]
    },
    {
      "name": "48",
      "direction": "DOWN",
      "connectorId": "RJ45_f",
      "compatibleSignalTypes": ["100BASE_TX", "1000BASE_T"]
    }
  ],
  "moduleSlotTypes": [
    {
      "name": "Management",
      "compatibleModuleSlotFormFactors": ["sfp"],
      "compatibleModuleTypes": [],
      "incompatibleModuleTypes": []
    },
    {
      "name": "49",
      "compatibleModuleSlotFormFactors": ["sfp", "sfpplus", "sfp28"],
      "compatibleModuleTypes": [],
      "incompatibleModuleTypes": []
    },
    {
      "name": "50",
      "compatibleModuleSlotFormFactors": ["sfp", "sfpplus", "sfp28"],
      "compatibleModuleTypes": [],
      "incompatibleModuleTypes": []
    },
    {
      "name": "51",
      "compatibleModuleSlotFormFactors": ["sfp", "sfpplus", "sfp28"],
      "compatibleModuleTypes": [],
      "incompatibleModuleTypes": []
    },
    {
      "name": "52",
      "compatibleModuleSlotFormFactors": ["sfp", "sfpplus", "sfp28"],
      "compatibleModuleTypes": [],
      "incompatibleModuleTypes": []
    },
    {
      "name": "53",
      "compatibleModuleSlotFormFactors": ["qsfpplus", "qsfp28"],
      "compatibleModuleTypes": [],
      "incompatibleModuleTypes": []
    },
    {
      "name": "54",
      "compatibleModuleSlotFormFactors": ["qsfpplus", "qsfp28"],
      "compatibleModuleTypes": [],
      "incompatibleModuleTypes": []
    }
  ]
}

=== jan-ldwg/site_manager_templates/devicetypes/riedel/riedel-esp-1216hl.json
{
  "version": "1.0",
  "id": "riedel-esp-1216hl",
  "name": "ESP-1216HL",
  "manufacturerId": "riedel",
  "orderCode": null,
  "orderNumber": "1220700",
  "climateLoad": 15,
  "rackType": "19INCH",
  "rackHeight": 1,
  "rackDepth": 95,
  "portTypes": [
    {
      "name": "EXP I/O",
      "direction": "IN",
      "connectorId": "RJ45_f",
      "compatibleSignalTypes": ["riedel_EXPANSION"]
    },
    {
      "name": "EXP I/O",
      "direction": "OUT",
      "connectorId": "RJ45_f",
      "compatibleSignalTypes": ["riedel_EXPANSION"]
    }
  ],
  "moduleSlotTypes": []
}

=== jan-ldwg/site_manager_templates/devicetypes/cedar/cedar-dns-8d.json
{
  "version": "1.0",
  "id": "cedar-dns-8d",
  "name": "DNS 8D",
  "manufacturerId": "cedar",
  "orderCode": null,
  "orderNumber": null,
  "climateLoad": 15,
  "rackType": "19INCH",
  "rackHeight": 1,
  "rackDepth": 200,
  "portTypes": [
    {
      "name": "CONTROL",
      "direction": "UP",
      "connectorId": "RJ45_f",
      "compatibleSignalTypes": ["100BASE_TX", "1000BASE_T"]
    },
    {
      "name": "Dante PRIMARY",
      "direction": "UP",
      "connectorId": "RJ45_f",
      "compatibleSignalTypes": ["100BASE_TX", "1000BASE_T"]
    },
    {
      "name": "Dante SECONDARY",
      "direction": "UP",
      "connectorId": "RJ45_f",
      "compatibleSignalTypes": ["100BASE_TX", "1000BASE_T"]
    },
    {
      "name": "AES IN/OUT (AES59)",
      "direction": "BIDI",
      "connectorId": "DSUB25p_f",
      "compatibleSignalTypes": ["AES59_DIGI_IO"]
    }
  ],
  "moduleSlotTypes": []
}

=== jan-ldwg/site_manager_templates/devicetypes/netgear/netgear-m4300-52g-poe-plus.json
{
  "version": "1.0",
  "id": "netgear-m4300-52g-poe-plus",
  "name": "M4300-52G-PoE+",
  "manufacturerId": "netgear",
  "orderCode": null,
  "orderNumber": "GSM4352PB",
  "climateLoad": 888,
  "rackType": "19INCH",
  "rackHeight": 1,
  "rackDepth": 388,
  "portTypes": [
    {
      "name": "USB",
      "direction": "OUT",
      "connectorId": "USB2.0A_f",
      "compatibleSignalTypes": ["USB_1", "USB_11", "USB_2"]
    },
    {
      "name": "Console (USB)",
      "direction": "IN",
      "connectorId": "USB2.0B_MINI_f",
      "compatibleSignalTypes": ["RS_232"]
    },
    {
      "name": "Console",
      "direction": "IN",
      "connectorId": "RJ45_f",
      "compatibleSignalTypes": ["RS_232"]
    },
    {
      "name": "OOB",
      "direction": "UP",
      "connectorId": "RJ45_f",
      "compatibleSignalTypes": ["1000BASE_T"]
    },
    {
      "name": "1",
      "direction": "DOWN",
      "connectorId": "RJ45_f",
      "compatibleSignalTypes": ["100BASE_TX", "1000BASE_T"]
    },
    {
      "name": "2",
      "direction": "DOWN",
      "connectorId": "RJ45_f",
      "compatibleSignalTypes": ["100BASE_TX", "1000BASE_T"]
    },
    {
      "name": "3",
      "direction": "DOWN",
      "connectorId": "RJ45_f",
      "compatibleSignalTypes": ["100BASE_TX", "1000BASE_T"]
    },
    {
      "name": "4",
      "direction": "DOWN",
      "connectorId": "RJ45_f",
      "compatibleSignalTypes": ["100BASE_TX", "1000BASE_T"]
    },
    {
      "name": "5",
      "direction": "DOWN",
      "connectorId": "RJ45_f",
      "compatibleSignalTypes": ["100BASE_TX", "1000BASE_T"]
    },
    {
      "name": "6",
      "direction": "DOWN",
      "connectorId": "RJ45_f",
      "compatibleSignalTypes": ["100BASE_TX", "1000BASE_T"]
    },
    {
      "name": "7",
      "direction": "DOWN",
      "connectorId": "RJ45_f",
      "compatibleSignalTypes": ["100BASE_TX", "1000BASE_T"]
    },
    {
      "name": "8",
      "direction": "DOWN",
      "connectorId": "RJ45_f",
      "compatibleSignalTypes": ["100BASE_TX", "1000BASE_T"]
    },
    {
      "name": "9",
      "direction": "DOWN",
      "connectorId": "RJ45_f",
      "compatibleSignalTypes": ["100BASE_TX", "1000BASE_T"]
    },
    {
      "name": "10",
      "direction": "DOWN",
      "connectorId": "RJ45_f",
      "compatibleSignalTypes": ["100BASE_TX", "1000BASE_T"]
    },
    {
      "name": "11",
      "direction": "DOWN",
      "connectorId": "RJ45_f",
      "compatibleSignalTypes": ["100BASE_TX", "1000BASE_T"]
    },
    {
      "name": "12",
      "direction": "DOWN",
      "connectorId": "RJ45_f",
      "compatibleSignalTypes": ["100BASE_TX", "1000BASE_T"]
    },
    {
      "name": "13",
      "direction": "DOWN",
      "connectorId": "RJ45_f",
      "compatibleSignalTypes": ["100BASE_TX", "1000BASE_T"]
    },
    {
      "name": "14",
      "direction": "DOWN",
      "connectorId": "RJ45_f",
      "compatibleSignalTypes": ["100BASE_TX", "1000BASE_T"]
    },
    {
      "name": "15",
      "direction": "DOWN",
      "connectorId": "RJ45_f",
      "compatibleSignalTypes": ["100BASE_TX", "1000BASE_T"]
    },
    {
      "name": "16",
      "direction": "DOWN",
      "connectorId": "RJ45_f",
      "compatibleSignalTypes": ["100BASE_TX", "1000BASE_T"]
    },
    {
      "name": "17",
      "direction": "DOWN",
      "connectorId": "RJ45_f",
      "compatibleSignalTypes": ["100BASE_TX", "1000BASE_T"]
    },
    {
      "name": "18",
      "direction": "DOWN",
      "connectorId": "RJ45_f",
      "compatibleSignalTypes": ["100BASE_TX", "1000BASE_T"]
    },
    {
      "name": "19",
      "direction": "DOWN",
      "connectorId": "RJ45_f",
      "compatibleSignalTypes": ["100BASE_TX", "1000BASE_T"]
    },
    {
      "name": "20",
      "direction": "DOWN",
      "connectorId": "RJ45_f",
      "compatibleSignalTypes": ["100BASE_TX", "1000BASE_T"]
    },
    {
      "name": "21",
      "direction": "DOWN",
      "connectorId": "RJ45_f",
      "compatibleSignalTypes": ["100BASE_TX", "1000BASE_T"]
    },
    {
      "name": "22",
      "direction": "DOWN",
      "connectorId": "RJ45_f",
      "compatibleSignalTypes": ["100BASE_TX", "1000BASE_T"]
    },
    {
      "name": "23",
      "direction": "DOWN",
      "connectorId": "RJ45_f",
      "compatibleSignalTypes": ["100BASE_TX", "1000BASE_T"]
    },
    {
      "name": "24",
      "direction": "DOWN",
      "connectorId": "RJ45_f",
      "compatibleSignalTypes": ["100BASE_TX", "1000BASE_T"]
    },
    {
      "name": "25",
      "direction": "DOWN",
      "connectorId": "RJ45_f",
      "compatibleSignalTypes": ["100BASE_TX", "1000BASE_T"]
    },
    {
      "name": "26",
      "direction": "DOWN",
      "connectorId": "RJ45_f",
      "compatibleSignalTypes": ["100BASE_TX", "1000BASE_T"]
    },
    {
      "name": "27",
      "direction": "DOWN",
      "connectorId": "RJ45_f",
      "compatibleSignalTypes": ["100BASE_TX", "1000BASE_T"]
    },
    {
      "name": "28",
      "direction": "DOWN",
      "connectorId": "RJ45_f",
      "compatibleSignalTypes": ["100BASE_TX", "1000BASE_T"]
    },
    {
      "name": "29",
      "direction": "DOWN",
      "connectorId": "RJ45_f",
      "compatibleSignalTypes": ["100BASE_TX", "1000BASE_T"]
    },
    {
      "name": "30",
      "direction": "DOWN",
      "connectorId": "RJ45_f",
      "compatibleSignalTypes": ["100BASE_TX", "1000BASE_T"]
    },
    {
      "name": "31",
      "direction": "DOWN",
      "connectorId": "RJ45_f",
      "compatibleSignalTypes": ["100BASE_TX", "1000BASE_T"]
    },
    {
      "name": "32",
      "direction": "DOWN",
      "connectorId": "RJ45_f",
      "compatibleSignalTypes": ["100BASE_TX", "1000BASE_T"]
    },
    {
      "name": "33",
      "direction": "DOWN",
      "connectorId": "RJ45_f",
      "compatibleSignalTypes": ["100BASE_TX", "1000BASE_T"]
    },
    {
      "name": "34",
      "direction": "DOWN",
      "connectorId": "RJ45_f",
      "compatibleSignalTypes": ["100BASE_TX", "1000BASE_T"]
    },
    {
      "name": "35",
      "direction": "DOWN",
      "connectorId": "RJ45_f",
      "compatibleSignalTypes": ["100BASE_TX", "1000BASE_T"]
    },
    {
      "name": "36",
      "direction": "DOWN",
      "connectorId": "RJ45_f",
      "compatibleSignalTypes": ["100BASE_TX", "1000BASE_T"]
    },
    {
      "name": "37",
      "direction": "DOWN",
      "connectorId": "RJ45_f",
      "compatibleSignalTypes": ["100BASE_TX", "1000BASE_T"]
    },
    {
      "name": "38",
      "direction": "DOWN",
      "connectorId": "RJ45_f",
      "compatibleSignalTypes": ["100BASE_TX", "1000BASE_T"]
    },
    {
      "name": "39",
      "direction": "DOWN",
      "connectorId": "RJ45_f",
      "compatibleSignalTypes": ["100BASE_TX", "1000BASE_T"]
    },
    {
      "name": "40",
      "direction": "DOWN",
      "connectorId": "RJ45_f",
      "compatibleSignalTypes": ["100BASE_TX", "1000BASE_T"]
    },
    {
      "name": "41",
      "direction": "DOWN",
      "connectorId": "RJ45_f",
      "compatibleSignalTypes": ["100BASE_TX", "1000BASE_T"]
    },
    {
      "name": "42",
      "direction": "DOWN",
      "connectorId": "RJ45_f",
      "compatibleSignalTypes": ["100BASE_TX", "1000BASE_T"]
    },
    {
      "name": "43",
      "direction": "DOWN",
      "connectorId": "RJ45_f",
      "compatibleSignalTypes": ["100BASE_TX", "1000BASE_T"]
    },
    {
      "name": "44",
      "direction": "DOWN",
      "connectorId": "RJ45_f",
      "compatibleSignalTypes": ["100BASE_TX", "1000BASE_T"]
    },
    {
      "name": "45",
      "direction": "DOWN",
      "connectorId": "RJ45_f",
      "compatibleSignalTypes": ["100BASE_TX", "1000BASE_T"]
    },
    {
      "name": "46",
      "direction": "DOWN",
      "connectorId": "RJ45_f",
      "compatibleSignalTypes": ["100BASE_TX", "1000BASE_T"]
    },
    {
      "name": "47",
      "direction": "DOWN",
      "connectorId": "RJ45_f",
      "compatibleSignalTypes": ["100BASE_TX", "1000BASE_T"]
    },
    {
      "name": "48",
      "direction": "DOWN",
      "connectorId": "RJ45_f",
      "compatibleSignalTypes": ["100BASE_TX", "1000BASE_T"]
    },
    {
      "name": "49",
      "direction": "DOWN",
      "connectorId": "RJ45_f",
      "compatibleSignalTypes": ["100BASE_TX", "1000BASE_T", "10GBASE_T"]
    },
    {
      "name": "50",
      "direction": "DOWN",
      "connectorId": "RJ45_f",
      "compatibleSignalTypes": ["100BASE_TX", "1000BASE_T", "10GBASE_T"]
    }
  ],
  "moduleSlotTypes": [
    {
      "name": "51",
      "compatibleModuleSlotFormFactors": ["sfp", "sfpplus"],
      "compatibleModuleTypes": [
        "netgear-agm731f",
        "netgear-agm732f",
        "netgear-agm734",
        "netgear-axm761",
        "netgear-axm762",
        "netgear-axm763",
        "netgear-axm764",
        "netgear-axm765"
      ],
      "incompatibleModuleTypes": []
    },
    {
      "name": "52",
      "compatibleModuleSlotFormFactors": ["sfp", "sfpplus"],
      "compatibleModuleTypes": [
        "netgear-agm731f",
        "netgear-agm732f",
        "netgear-agm734",
        "netgear-axm761",
        "netgear-axm762",
        "netgear-axm763",
        "netgear-axm764",
        "netgear-axm765"
      ],
      "incompatibleModuleTypes": []
    }
  ]
}
