=== jan-ldwg/site_manager_templates/schemas/moduletype.schema.json
{
  "$schema": "https://json-schema.org/draft/2020-12/schema",
  "title": "moduletype",
  "description": "JSON document describing a new module type",
  "type": "object",
  "properties": {
    "version": {
      "description": "Version number of the template. Minor version must be increased with every change. Major version must only be changed when targeting a different API version.",
      "type": "string",
      "pattern": "^\\d{1,2}\\.\\d{1,2}$"
    },
    "id": {
      "description": "Id of the module type. Consists of id of manufacturer followed by id of module type. See documentation for rules.",
      "type": "string",
      "pattern": "^(?=.{1,48}$)(?!.*--)[a-z](?:[a-z-]{0,14}[a-z])?-[a-z0-9](?:[a-z0-9-]*[a-z0-9])?$",
      "maxLength": 48
    },
    "name": {
      "description": "Name of the module as given by manufacturer",
      "type": "string",
      "maxLength": 256
    },
    "manufacturerId": {
      "description": "Id of the manufacturer of the device type.",
      "type": "string",
      "pattern": "^(?!.*--)[a-z](?:[a-z-]{0,14}[a-z])$",
      "maxLength": 16
    },
    "orderCode": {
      "description": "Order code for the device type as used by the manufacturer.",
      "type": ["string", "null"]
    },
    "orderNumber": {
      "description": "Order number for the device type as used by the manufacturer.",
      "type": ["string", "null"]
    },
    "moduleFormFactorId": {
      "description": "Form factor of the module.",
      "type": ["string", "null"],
      "pattern": "^[a-z0-9]+(?:-[a-z0-9]+)*$"
    },
    "spanWidth": {
      "description": "The width of the module in slots",
      "type": "integer"
    },
    "portTypes": {
      "description": "List of all types of ports on the module type.",
      "type": "array",
      "items": {
        "type": "object",
        "properties": {
          "name": {
            "description": "Name of the port, as printed on the module.",
            "type": "string"
          },
          "direction": {
            "description": "Direction of the port type. See documentation for explainations of the possible values.",
            "enum": [
              "IN",
              "OUT",
              "INOUT",
              "BIDI",
              "UP",
              "DOWN",
              "FRONT",
              "REAR"
            ]
          },
          "connectorId": {
            "description": "Id of the connector.",
            "type": "string",
            "pattern": "^[A-Za-z0-9](?:[A-Za-z0-9]|[_.](?=[A-Za-z0-9]))*_(?:f|m|h)$"
          },
          "compatibleSignalTypes": {
            "description": "List of signal types that are compatible with this port.",
            "type": "array",
            "items": {
              "type": "string",
              "pattern": "^(?!.*--)(?:[a-z](?:[a-z-]{0,14}[a-z])?_)?[A-Z0-9]+(?:_[A-Z0-9]+)*$"
            },
            "uniqueItems": true
          }
        },
        "required": [
          "name",
          "direction",
          "connectorId",
          "compatibleSignalTypes"
        ],
        "additionalProperties": false
      }
    },
    "moduleSlotTypes": {
      "description": "List of all types of module slots on the module type.",
      "type": "array",
      "items": {
        "type": "object",
        "properties": {
          "name": {
            "description": "Name of the module slot, as labeled on the module.",
            "type": "string"
          },
          "canSpan": {
            "description": "Indicates wether a module can span into the next slot",
            "type": "boolean"
          },
          "compatibleModuleSlotFormFactors": {
            "description": "List of module slot factors that can physically fit into the slot.",
            "type": "array",
            "uniqueItems": true,
            "items": {
              "type": "string",
              "pattern": "^[a-z0-9]+(?:-[a-z0-9]+)*$"
            }
          },
          "compatibleModuleTypes": {
            "description": "List of module types that are guranteed by the manufacturer to work in this slot.",
            "type": "array",
            "uniqueItems": true,
            "items": {
              "type": "string",
              "pattern": "^(?=.{1,48}$)(?!.*--)[a-z](?:[a-z-]{0,14}[a-z])?-[a-z0-9](?:[a-z0-9-]*[a-z0-9])?$"
            }
          },
          "incompatibleModuleTypes": {
            "description": "List of module types that are guranteed by the manufacturer not work in this module slot.",
            "type": "array",
            "uniqueItems": true,
            "items": {
              "type": "string",
              "pattern": "^(?=.{1,48}$)(?!.*--)[a-z](?:[a-z-]{0,14}[a-z])?-[a-z0-9](?:[a-z0-9-]*[a-z0-9])?$"
            }
          }
        },
        "required": [
          "name",
          "compatibleModuleSlotFormFactors",
          "compatibleModuleTypes",
          "incompatibleModuleTypes"
        ],
        "additionalProperties": false
      }
    }
  },
  "required": ["version", "id", "name", "manufacturerId"],
  "additionalProperties": false
}

=== jan-ldwg/site_manager_templates/moduletypes/lawo/lawo-vx-module-dark.json
{
  "version": "1.0",
  "id": "lawo-vx-module-dark",
  "name": "Virtual Extension Dark",
  "orderCode": null,
  "orderNumber": "711/30-D",
  "moduleFormFactorId": "",
  "manufacturerId": "lawo",
  "portTypes": [
    {
      "name": "Display Port",
      "direction": "IN",
      "connectorId": "DISPLAYPORT_f",
      "compatibleSignalTypes": ["DP_10", "DP_11"]
    },
    {
      "name": "USB",
      "direction": "IN",
      "connectorId": "USB2.0B_f",
      "compatibleSignalTypes": ["USB_1", "USB_11", "USB_2"]
    }
  ]
}

=== jan-ldwg/site_manager_templates/moduletypes/directout/directout-scio-sm.json
{
  "version": "1.0",
  "id": "directout-scio-sm",
  "name": "SC.IO SM",
  "orderCode": null,
  "orderNumber": "DOMIO0008",
  "moduleFormFactorId": "directout-b-slot",
  "manufacturerId": "directout",
  "portTypes": [
    {
      "name": "IN",
      "direction": "IN",
      "connectorId": "SC_SPLX_PC_SM_f",
      "compatibleSignalTypes": ["MADI_SM_1310"]
    },
    {
      "name": "OUT",
      "direction": "OUT",
      "connectorId": "SC_SPLX_PC_SM_f",
      "compatibleSignalTypes": ["MADI_SM_1310"]
    }
  ]
}

=== jan-ldwg/site_manager_templates/moduletypes/ross/ross-sfp-hdm-in-12g.json
{
  "version": "1.0",
  "name": "SFP-HDM-IN-12G",
  "id": "ross-sfp-hdm-in-12g",
  "orderCode": null,
  "orderNumber": "SFP-HDM-IN-12G",
  "moduleFormFactorId": "sfp",
  "manufacturerId": "ross",
  "portTypes": [
    {
      "name": "",
      "direction": "IN",
      "connectorId": "HDMI_D_f",
      "compatibleSignalTypes": ["HDMI", "DVI_D", "DVI_I"]
    }
  ]
}

=== jan-ldwg/site_manager_templates/moduletypes/lawo/lawo-98160-82.json
{
  "version": "1.0",
  "name": "981/60-82",
  "id": "lawo-98160-82",
  "orderCode": null,
  "orderNumber": "981/60-82",
  "moduleFormFactorId": "sfp",
  "manufacturerId": "lawo",
  "portTypes": [
    {
      "name": "",
      "direction": "IN",
      "connectorId": "HD_BNC_f",
      "compatibleSignalTypes": ["MADI_CU"]
    },
    {
      "name": "",
      "direction": "OUT",
      "connectorId": "HD_BNC_f",
      "compatibleSignalTypes": ["MADI_CU"]
    }
  ]
}

=== jan-ldwg/site_manager_templates/moduletypes/directout/directout-milansgsrcio.json
{
  "version": "1.0",
  "id": "directout-milansgsrcio",
  "name": "MILAN.SG.SRC.IO",
  "orderCode": null,
  "orderNumber": "DONETAS01",
  "moduleFormFactorId": "directout-a-slot",
  "manufacturerId": "directout",
  "portTypes": [
    {
      "name": "MILAN PORT 1",
      "direction": "UP",
      "connectorId": "RJ45_f",
      "compatibleSignalTypes": ["1000BASE_T"]
    },
    {
      "name": "MILAN PORT 2",
      "direction": "UP",
      "connectorId": "RJ45_f",
      "compatibleSignalTypes": ["1000BASE_T"]
    },
    {
      "name": "SOUNDGRID PORT 1",
      "direction": "UP",
      "connectorId": "RJ45_f",
      "compatibleSignalTypes": ["1000BASE_T"]
    },
    {
      "name": "SOUNDGRID PORT 2",
      "direction": "UP",
      "connectorId": "RJ45_f",
      "compatibleSignalTypes": ["1000BASE_T"]
    }
  ]
}

=== jan-ldwg/site_manager_templates/moduletypes/directout/directout-usbio.json
{
  "version": "1.0",
  "id": "directout-usbio",
  "name": "USB.IO",
  "orderCode": null,
  "orderNumber": "DOUSBIO01",
  "moduleFormFactorId": "directout-a-slot",
  "manufacturerId": "directout",
  "portTypes": [
    {
      "name": "USB",
      "direction": "IN",
      "connectorId": "USBC_f",
      "compatibleSignalTypes": ["USB_2", "USB_32_GEN1X1"]
    }
  ]
}

=== jan-ldwg/site_manager_templates/moduletypes/netgear/netgear-axm761.json
{
  "version": "1.0",
  "id": "netgear-axm761",
  "name": "AXM761",
  "orderCode": null,
  "orderNumber": null,
  "moduleFormFactorId": "sfpplus",
  "manufacturerId": "netgear",
  "portTypes": [
    {
      "name": "",
      "direction": "UP",
      "connectorId": "LC_DPLX_PC_MM_f",
      "compatibleSignalTypes": ["10GBASE_SR"]
    }
  ]
}

=== jan-ldwg/site_manager_templates/moduletypes/lynx/lynx-dva-5718-l.json
{
  "version": "1.0",
  "id": "lynx-dva-5718-l",
  "name": "DVA 5718 L",
  "orderCode": null,
  "orderNumber": "4250479321601",
  "moduleFormFactorId": "lynx-5000-active",
  "spanWidth": 1,
  "manufacturerId": "lynx",
  "portTypes": [
    {
      "name": "IN",
      "direction": "IN",
      "connectorId": "BNC_f",
      "compatibleSignalTypes": ["BLACK_BURST", "TRI_SYNC"]
    },
    {
      "name": "Loop OUT",
      "direction": "OUT",
      "connectorId": "BNC_f",
      "compatibleSignalTypes": ["BLACK_BURST", "TRI_SYNC"]
    },
    {
      "name": "OUT 1",
      "direction": "OUT",
      "connectorId": "BNC_f",
      "compatibleSignalTypes": ["BLACK_BURST", "TRI_SYNC"]
    },
    {
      "name": "OUT 2",
      "direction": "OUT",
      "connectorId": "BNC_f",
      "compatibleSignalTypes": ["BLACK_BURST", "TRI_SYNC"]
    },
    {
      "name": "OUT 3",
      "direction": "OUT",
      "connectorId": "BNC_f",
      "compatibleSignalTypes": ["BLACK_BURST", "TRI_SYNC"]
    },
    {
      "name": "OUT 4",
      "direction": "OUT",
      "connectorId": "BNC_f",
      "compatibleSignalTypes": ["BLACK_BURST", "TRI_SYNC"]
    },
    {
      "name": "OUT 5",
      "direction": "OUT",
      "connectorId": "BNC_f",
      "compatibleSignalTypes": ["BLACK_BURST", "TRI_SYNC"]
    },
    {
      "name": "OUT 6",
      "direction": "OUT",
      "connectorId": "BNC_f",
      "compatibleSignalTypes": ["BLACK_BURST", "TRI_SYNC"]
    },
    {
      "name": "OUT 7",
      "direction": "OUT",
      "connectorId": "BNC_f",
      "compatibleSignalTypes": ["BLACK_BURST", "TRI_SYNC"]
    },
    {
      "name": "OUT 8",
      "direction": "OUT",
      "connectorId": "BNC_f",
      "compatibleSignalTypes": ["BLACK_BURST", "TRI_SYNC"]
    }
  ],
  "moduleSlotTypes": []
}
