=== jan-ldwg/site_manager_templates/schemas/moduletype.schema.json
{
  "$schema": "https://json-schema.org/draft/2020-12/schema",
  "title": "moduletype",
  "description": "JSON document describing a new module type",
  "type": "object",
  "properties": {
    "version": {
      "description": "Version number of the template. Minor version must be increased with every change. Major version must only be changed when targeting a different API version.",
      "type": "string",
      "pattern": "^\\d{1,2}\\.\\d{1,2}$"
    },
    "id": {
      "description": "Id of the module type. Consists of id of manufacturer followed by id of module type. See documentation for rules.",
      "type": "string",
      "pattern": "^(?=.{1,48}$)(?!.*--)[a-z](?:[a-z-]{0,14}[a-z])?-[a-z0-9](?:[a-z0-9-]*[a-z0-9])?$",
      "maxLength": 48
    },
    "name": {
      "description": "Name of the module as given by manufacturer",
      "type": "string",
      "maxLength": 256
    },
    "manufacturerId": {
      "description": "Id of the manufacturer of the device type.",
      "type": "string",
      "pattern": "^(?!.*--)[a-z](?:[a-z-]{0,14}[a-z])$",
      "maxLength": 16
    },
    "orderCode": {
      "description": "Order code for the device type as used by the manufacturer.",
      "type": ["string", "null"]
    },
    "orderNumber": {
      "description": "Order number for the device type as used by the manufacturer.",
      "type": ["string", "null"]
    },
    "moduleFormFactorId": {
      "description": "Form factor of the module.",
      "type": ["string", "null"],
      "pattern": "^[a-z0-9]+(?:-[a-z0-9]+)*$"
    },
    "spanWidth": {
      "description": "The width of the module in slots",
      "type": "integer"
    },
    "portTypes": {
      "description": "List of all types of ports on the module type.",
      "type": "array",
      "items": {
        "type": "object",
        "properties": {
          "name": {
            "description": "Name of the port, as printed on the module.",
            "type": "string"
          },
          "direction": {
            "description": "Direction of the port type. See documentation for explainations of the possible values.",
            "enum": [
              "IN",
              "OUT",
              "INOUT",
              "BIDI",
              "UP",
              "DOWN",
              "FRONT",
              "REAR"
            ]
          },
          "connectorId": {
            "description": "Id of the connector.",
            "type": "string",
            "pattern": "^[A-Za-z0-9](?:[A-Za-z0-9]|[_.](?=[A-Za-z0-9]))*_(?:f|m|h)$"
          },
          "compatibleSignalTypes": {
            "description": "List of signal types that are compatible with this port.",
            "type": "array",
            "items": {
              "type": "string",
              "pattern": "^(?!.*--)(?:[a-z](?:[a-z-]{0,14}[a-z])?_)?[A-Z0-9]+(?:_[A-Z0-9]+)*$"
            },
            "uniqueItems": true
          }
        },
        "required": [
          "name",
          "direction",
          "connectorId",
          "compatibleSignalTypes"
        ],
        "additionalProperties": false
      }
    },
    "moduleSlotTypes": {
      "description": "List of all types of module slots on the module type.",
      "type": "array",
      "items": {
        "type": "object",
        "properties": {
          "name": {
            "description": "Name of the module slot, as labeled on the module.",
            "type": "string"
          },
          "canSpan": {
            "description": "Indicates wether a module can span into the next slot",
            "type": "boolean"
          },
          "compatibleModuleSlotFormFactors": {
            "description": "List of module slot factors that can physically fit into the slot.",
            "type": "array",
            "uniqueItems": true,
            "items": {
              "type": "string",
              "pattern": "^[a-z0-9]+(?:-[a-z0-9]+)*$"
            }
          },
          "compatibleModuleTypes": {
            "description": "List of module types that are guranteed by the manufacturer to work in this slot.",
            "type": "array",
            "uniqueItems": true,
            "items": {
              "type": "string",
              "pattern": "^(?=.{1,48}$)(?!.*--)[a-z](?:[a-z-]{0,14}[a-z])?-[a-z0-9](?:[a-z0-9-]*[a-z0-9])?$"
            }
          },
          "incompatibleModuleTypes": {
            "description": "List of module types that are guranteed by the manufacturer not work in this module slot.",
            "type": "array",
            "uniqueItems": true,
            "items": {
              "type": "string",
              "pattern": "^(?=.{1,48}$)(?!.*--)[a-z](?:[a-z-]{0,14}[a-z])?-[a-z0-9](?:[a-z0-9-]*[a-z0-9])?$"
            }
          }
        },
        "required": [
          "name",
          "compatibleModuleSlotFormFactors",
          "compatibleModuleTypes",
          "incompatibleModuleTypes"
        ],
        "additionalProperties": false
      }
    }
  },
  "required": ["version", "id", "name", "manufacturerId"],
  "additionalProperties": false
}

=== jan-ldwg/site_manager_templates/moduletypes/lawo/lawo-98160-20.json
{
  "version": "1.0",
  "id": "lawo-98160-20",
  "name": "981/60-20",
  "orderCode": null,
  "orderNumber": "981/60-20",
  "moduleFormFactorId": "sfp",
  "manufacturerId": "lawo",
  "portTypes": [
    {
      "name": "",
      "direction": "UP",
      "connectorId": "LC_DPLX_PC_SM_f",
      "compatibleSignalTypes": ["1000BASE_LX"]
    }
  ]
}

=== jan-ldwg/site_manager_templates/moduletypes/lynx/lynx-rct-5023g.json
{
  "version": "1.0",
  "id": "lynx-rct-5023g",
  "name": "RCT 5023-G",
  "orderCode": null,
  "orderNumber": "4250479321434",
  "moduleFormFactorId": null,
  "manufacturerId": "lynx",
  "portTypes": [],
  "moduleSlotTypes": [
    {
      "name": "",
      "compatibleModuleSlotFormFactors": [],
      "compatibleModuleTypes": ["lynx-oh-rct5023-svr"],
      "incompatibleModuleTypes": []
    }
  ]
}

=== jan-ldwg/site_manager_templates/moduletypes/directout/directout-bncio.json
{
  "version": "1.0",
  "id": "directout-bncio",
  "name": "BNC.IO",
  "orderCode": null,
  "orderNumber": "DOMIO0005",
  "moduleFormFactorId": "directout-b-slot",
  "manufacturerId": "directout",
  "portTypes": [
    {
      "name": "IN",
      "direction": "IN",
      "connectorId": "BNC_f",
      "compatibleSignalTypes": ["MADI_CU"]
    },
    {
      "name": "OUT",
      "direction": "OUT",
      "connectorId": "BNC_f",
      "compatibleSignalTypes": ["MADI_CU"]
    }
  ]
}

=== jan-ldwg/site_manager_templates/moduletypes/directout/directout-mic8hdio.json
{
  "version": "1.0",
  "id": "directout-mic8hdio",
  "name": "MIC8.HD.IO",
  "orderCode": null,
  "orderNumber": "DOAIO0025",
  "moduleFormFactorId": "directout-c-slot",
  "manufacturerId": "directout",
  "portTypes": [
    {
      "name": "MIC/LINE INPUT",
      "direction": "IN",
      "connectorId": "DSUB25p_f",
      "compatibleSignalTypes": ["AES59_ANA"]
    },
    {
      "name": "LINE OUTPUT",
      "direction": "OUT",
      "connectorId": "DSUB25p_f",
      "compatibleSignalTypes": ["AES59_ANA"]
    }
  ]
}

=== jan-ldwg/site_manager_templates/moduletypes/lawo/lawo-98160-80.json
{
  "version": "1.1",
  "id": "lawo-98160-80",
  "name": "981/60-80",
  "orderCode": null,
  "orderNumber": "981/60-80",
  "moduleFormFactorId": "sfp",
  "manufacturerId": "lawo",
  "portTypes": [
    {
      "name": "",
      "direction": "BIDI",
      "connectorId": "LC_DPLX_PC_MM_f",
      "compatibleSignalTypes": ["MADI_MM_1310"]
    }
  ]
}

=== jan-ldwg/site_manager_templates/moduletypes/directout/directout-sfpio.json
{
  "version": "1.0",
  "id": "directout-sfpio",
  "name": "SFP.IO",
  "orderCode": null,
  "orderNumber": "DOMIO0017",
  "moduleFormFactorId": "directout-b-slot",
  "manufacturerId": "directout",
  "moduleSlotTypes": [
    {
      "name": "",
      "compatibleModuleSlotFormFactors": ["sfp"],
      "compatibleModuleTypes": [
        "directout-sfp-madi-bnc",
        "directout-sfp-madi-mm",
        "directout-sfp-madi-sm",
        "directout-usbmadi"
      ],
      "incompatibleModuleTypes": []
    }
  ]
}

=== jan-ldwg/site_manager_templates/moduletypes/directout/directout-sfp-madi-mm.json
{
  "version": "1.0",
  "id": "directout-sfp-madi-mm",
  "name": "SFP MADI mm",
  "orderCode": null,
  "orderNumber": "DOICT0136",
  "moduleFormFactorId": "sfp",
  "manufacturerId": "directout",
  "portTypes": [
    {
      "name": "",
      "direction": "BIDI",
      "connectorId": "LC_DPLX_PC_MM_f",
      "compatibleSignalTypes": ["MADI_MM_1310"]
    }
  ]
}

=== jan-ldwg/site_manager_templates/moduletypes/telestream/telestream-mp-sfp-10gesr.json
{
  "version": "1.0",
  "id": "telestream-mp-sfp-10gesr",
  "name": "MP-SFP 10GESR",
  "orderCode": null,
  "orderNumber": null,
  "moduleFormFactorId": "sfpplus",
  "manufacturerId": "telestream",
  "portTypes": [
    {
      "name": "",
      "direction": "UP",
      "connectorId": "LC_DPLX_PC_MM_f",
      "compatibleSignalTypes": ["10GBASE_SR"]
    }
  ]
}
