=== jan-ldwg/site_manager_templates/schemas/moduletype.schema.json
{
  "$schema": "https://json-schema.org/draft/2020-12/schema",
  "title": "moduletype",
  "description": "JSON document describing a new module type",
  "type": "object",
  "properties": {
    "version": {
      "description": "Version number of the template. Minor version must be increased with every change. Major version must only be changed when targeting a different API version.",
      "type": "string",
      "pattern": "^\\d{1,2}\\.\\d{1,2}$"
    },
    "id": {
      "description": "Id of the module type. Consists of id of manufacturer followed by id of module type. See documentation for rules.",
      "type": "string",
      "pattern": "^(?=.{1,48}$)(?!.*--)[a-z](?:[a-z-]{0,14}[a-z])?-[a-z0-9](?:[a-z0-9-]*[a-z0-9])?$",
      "maxLength": 48
    },
    "name": {
      "description": "Name of the module as given by manufacturer",
      "type": "string",
      "maxLength": 256
    },
    "manufacturerId": {
      "description": "Id of the manufacturer of the device type.",
      "type": "string",
      "pattern": "^(?!.*--)[a-z](?:[a-z-]{0,14}[a-z])$",
      "maxLength": 16
    },
    "orderCode": {
      "description": "Order code for the device type as used by the manufacturer.",
      "type": ["string", "null"]
    },
    "orderNumber": {
      "description": "Order number for the device type as used by the manufacturer.",
      "type": ["string", "null"]
    },
    "moduleFormFactorId": {
      "description": "Form factor of the module.",
      "type": ["string", "null"],
      "pattern": "^[a-z0-9]+(?:-[a-z0-9]+)*$"
    },
    "spanWidth": {
      "description": "The width of the module in slots",
      "type": "integer"
    },
    "portTypes": {
      "description": "List of all types of ports on the module type.",
      "type": "array",
      "items": {
        "type": "object",
        "properties": {
          "name": {
            "description": "Name of the port, as printed on the module.",
            "type": "string"
          },
          "direction": {
            "description": "Direction of the port type. See documentation for explainations of the possible values.",
            "enum": [
              "IN",
              "OUT",
              "INOUT",
              "BIDI",
              "UP",
              "DOWN",
              "FRONT",
              "REAR"
            ]
          },
          "connectorId": {
            "description": "Id of the connector.",
            "type": "string",
            "pattern": "^[A-Za-z0-9](?:[A-Za-z0-9]|[_.](?=[A-Za-z0-9]))*_(?:f|m|h)$"
          },
          "compatibleSignalTypes": {
            "description": "List of signal types that are compatible with this port.",
            "type": "array",
            "items": {
              "type": "string",
              "pattern": "^(?!.*--)(?:[a-z](?:[a-z-]{0,14}[a-z])?_)?[A-Z0-9]+(?:_[A-Z0-9]+)*$"
            },
            "uniqueItems": true
          }
        },
        "required": [
          "name",
          "direction",
          "connectorId",
          "compatibleSignalTypes"
        ],
        "additionalProperties": false
      }
    },
    "moduleSlotTypes": {
      "description": "List of all types of module slots on the module type.",
      "type": "array",
      "items": {
        "type": "object",
        "properties": {
          "name": {
            "description": "Name of the module slot, as labeled on the module.",
            "type": "string"
          },
          "canSpan": {
            "description": "Indicates wether a module can span into the next slot",
            "type": "boolean"
          },
          "compatibleModuleSlotFormFactors": {
            "description": "List of module slot factors that can physically fit into the slot.",
            "type": "array",
            "uniqueItems": true,
            "items": {
              "type": "string",
              "pattern": "^[a-z0-9]+(?:-[a-z0-9]+)*$"
            }
          },
          "compatibleModuleTypes": {
            "description": "List of module types that are guranteed by the manufacturer to work in this slot.",
            "type": "array",
            "uniqueItems": true,
            "items": {
              "type": "string",
              "pattern": "^(?=.{1,48}$)(?!.*--)[a-z](?:[a-z-]{0,14}[a-z])?-[a-z0-9](?:[a-z0-9-]*[a-z0-9])?$"
            }
          },
          "incompatibleModuleTypes": {
            "description": "List of module types that are guranteed by the manufacturer not work in this module slot.",
            "type": "array",
            "uniqueItems": true,
            "items": {
              "type": "string",
              "pattern": "^(?=.{1,48}$)(?!.*--)[a-z](?:[a-z-]{0,14}[a-z])?-[a-z0-9](?:[a-z0-9-]*[a-z0-9])?$"
            }
          }
        },
        "required": [
          "name",
          "compatibleModuleSlotFormFactors",
          "compatibleModuleTypes",
          "incompatibleModuleTypes"
        ],
        "additionalProperties": false
      }
    }
  },
  "required": ["version", "id", "name", "manufacturerId"],
  "additionalProperties": false
}

=== jan-ldwg/site_manager_templates/moduletypes/ross/ross-sfp-hdm-in.json
{
  "version": "1.0",
  "name": "SFP-HDM-IN",
  "id": "ross-sfp-hdm-in",
  "orderCode": null,
  "orderNumber": "SFP-HDM-IN",
  "moduleFormFactorId": "sfp",
  "manufacturerId": "ross",
  "portTypes": [
    {
      "name": "",
      "direction": "IN",
      "connectorId": "HDMI_D_f",
      "compatibleSignalTypes": ["HDMI", "DVI_D", "DVI_I"]
    }
  ]
}

=== jan-ldwg/site_manager_templates/moduletypes/directout/directout-danteravsrcio.json
{
  "version": "1.0",
  "id": "directout-danteravsrcio",
  "name": "DANTE.RAV.SRC.IO",
  "orderCode": null,
  "orderNumber": "DONETDR01",
  "moduleFormFactorId": "directout-a-slot",
  "manufacturerId": "directout",
  "portTypes": [
    {
      "name": "PRI (1)",
      "direction": "UP",
      "connectorId": "RJ45_f",
      "compatibleSignalTypes": ["1000BASE_T"]
    },
    {
      "name": "SEC (2)",
      "direction": "UP",
      "connectorId": "RJ45_f",
      "compatibleSignalTypes": ["1000BASE_T"]
    },
    {
      "name": "PORT 1",
      "direction": "UP",
      "connectorId": "RJ45_f",
      "compatibleSignalTypes": ["1000BASE_T"]
    },
    {
      "name": "PORT 2",
      "direction": "UP",
      "connectorId": "RJ45_f",
      "compatibleSignalTypes": ["1000BASE_T"]
    }
  ]
}

=== jan-ldwg/site_manager_templates/moduletypes/imagine/imagine-opqsfpfr100g.json
{
  "version": "1.0",
  "id": "imagine-opqsfpfr100g",
  "name": "OP+QSFP+FR+100G",
  "orderCode": null,
  "orderNumber": "OP+QSFP+FR+100G",
  "moduleFormFactorId": "qsfp28",
  "manufacturerId": "imagine",
  "portTypes": [
    {
      "name": "",
      "direction": "UP",
      "connectorId": "LC_DPLX_PC_SM_f",
      "compatibleSignalTypes": ["100GBASE_FR1"]
    }
  ]
}

=== jan-ldwg/site_manager_templates/moduletypes/directout/directout-scio-mm.json
{
  "version": "1.0",
  "id": "directout-scio-mm",
  "name": "SC.IO MM",
  "orderCode": null,
  "orderNumber": "DOMIO0006",
  "moduleFormFactorId": "directout-b-slot",
  "manufacturerId": "directout",
  "portTypes": [
    {
      "name": "IN",
      "direction": "IN",
      "connectorId": "SC_SPLX_PC_MM_f",
      "compatibleSignalTypes": ["MADI_MM_1310"]
    },
    {
      "name": "OUT",
      "direction": "OUT",
      "connectorId": "SC_SPLX_PC_MM_f",
      "compatibleSignalTypes": ["MADI_MM_1310"]
    }
  ]
}

=== jan-ldwg/site_manager_templates/moduletypes/directout/directout-madi4srcio.json
{
  "version": "1.0",
  "id": "directout-madi4srcio",
  "name": "MADI4.SRC.IO",
  "orderCode": null,
  "orderNumber": "DOMIO0043",
  "moduleFormFactorId": "directout-a-slot",
  "manufacturerId": "directout",
  "moduleSlotTypes": [
    {
      "name": "MADI 1",
      "compatibleModuleSlotFormFactors": ["sfp"],
      "compatibleModuleTypes": [
        "directout-sfp-madi-bnc",
        "directout-sfp-madi-mm",
        "directout-sfp-madi-sm",
        "directout-usbmadi"
      ],
      "incompatibleModuleTypes": []
    },
    {
      "name": "MADI 2",
      "compatibleModuleSlotFormFactors": ["sfp"],
      "compatibleModuleTypes": [
        "directout-sfp-madi-bnc",
        "directout-sfp-madi-mm",
        "directout-sfp-madi-sm",
        "directout-usbmadi"
      ],
      "incompatibleModuleTypes": []
    },
    {
      "name": "MADI 3",
      "compatibleModuleSlotFormFactors": ["sfp"],
      "compatibleModuleTypes": [
        "directout-sfp-madi-bnc",
        "directout-sfp-madi-mm",
        "directout-sfp-madi-sm",
        "directout-usbmadi"
      ],
      "incompatibleModuleTypes": []
    },
    {
      "name": "MADI 4",
      "compatibleModuleSlotFormFactors": ["sfp"],
      "compatibleModuleTypes": [
        "directout-sfp-madi-bnc",
        "directout-sfp-madi-mm",
        "directout-sfp-madi-sm",
        "directout-usbmadi"
      ],
      "incompatibleModuleTypes": []
    }
  ]
}

=== jan-ldwg/site_manager_templates/moduletypes/ross/ross-sfp-fiber-3g.json
{
  "version": "1.0",
  "name": "SFP-FIBER-3G",
  "id": "ross-sfp-fiber-3g",
  "orderCode": null,
  "orderNumber": "SFP-FIBER-3G",
  "moduleFormFactorId": "sfp",
  "manufacturerId": "ross",
  "portTypes": [
    {
      "name": "RX",
      "direction": "IN",
      "connectorId": "LC_SPLX_PC_SM_f",
      "compatibleSignalTypes": [
        "SDI_SD_SM_1310",
        "SDI_HD_SM_1310",
        "SDI_3G_SM_1310"
      ]
    },
    {
      "name": "TX",
      "direction": "OUT",
      "connectorId": "LC_SPLX_PC_SM_f",
      "compatibleSignalTypes": [
        "SDI_SD_SM_1310",
        "SDI_HD_SM_1310",
        "SDI_3G_SM_1310"
      ]
    }
  ]
}

=== jan-ldwg/site_manager_templates/moduletypes/imagine/imagine-sfphdmiout.json
{
  "version": "1.1",
  "name": "SFP+HDMI+OUT",
  "id": "imagine-sfphdmiout",
  "orderCode": null,
  "orderNumber": "SFP+HDMI+OUT",
  "moduleFormFactorId": "sfp",
  "manufacturerId": "imagine",
  "portTypes": [
    {
      "name": "",
      "direction": "OUT",
      "connectorId": "HDMI_D_f",
      "compatibleSignalTypes": ["HDMI", "DVI_D", "DVI_I"]
    }
  ]
}

=== jan-ldwg/site_manager_templates/moduletypes/telestream/telestream-mp-sfp-10gelr.json
{
  "version": "1.0",
  "id": "telestream-mp-sfp-10gelr",
  "name": "MP-SFP 10GELR",
  "orderCode": null,
  "orderNumber": null,
  "moduleFormFactorId": "sfpplus",
  "manufacturerId": "telestream",
  "portTypes": [
    {
      "name": "",
      "direction": "UP",
      "connectorId": "LC_DPLX_PC_SM_f",
      "compatibleSignalTypes": ["10GBASE_LR"]
    }
  ]
}
